In [1]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib
import seaborn as sns
# import missingno as msno
# from plotnine import *
import folium

In [2]:
import requests
# from bs4 import BeautifulSoup
# from selenium import webdriver
import json
from pandas import json_normalize
import time

따릉이 서버에 post 방식으로 요청해서 따릉이 서버가 응답하는 데이터를 받는다.

In [3]:
response = requests.post(
    'https://www.bikeseoul.com/app/station/getStationRealtimeStatus.do',
    data = {
        'stationGrpSeq': 'ALL'
    }
)
# print(response) # <Response [200]>
# print(type(response.text)) # <class str>
print(response.text)

{"stationImgPath":"/nas_link/spb/attachFiles/file_admin/basePath","appUserSessionVO":{"encPwd":null,"usrClsCd":null,"usrDeviceId":null,"usrSeq":null,"voucherEndDttm":null,"voucherSeq":null,"usrType":null,"loginId":null,"usrMpnNo":null,"snsType":null,"mbId":null,"mpnLostYn":null,"lang":"LAG_001","appOsType":null,"orgType":null,"snsId":null,"viewFlg":"list","usrBirthDate":null,"sexCd":null,"rentEncPwd":null,"telecomClsCd":null,"authCiVal":null,"authClsCd":null,"mbTelNo":null,"mbEmailName":null,"mbPostNo":null,"mbAddr1":null,"mbAddr2":null,"parentSexCd":null,"parentBirthDate":null,"parentMpnNo":null,"emailSendAgreeYn":null,"lastLoginDttm":null,"mbWgt":null,"langClsCd":null,"leaveYn":null,"leaveReasonCd":null,"leaveDttm":null,"mbInfoColecAgreeDttm":null,"mpnLostDttm":null,"pagingYn":null,"usrIp":null,"partyVoucherSeq":null,"elecVoucherSeq":null,"requestSeq":null,"usrDeviceType":null,"authDiVal":null,"snsEmail":null,"tCardYn":null,"mCardYn":null,"mainType":null,"regDttm":null,"pageSize":0,"currentPageNo":1,"totalRecordCount":0,"recordCountPerPage":0,"firstRecordIndex":0,"searchValue":null,"searchParameter":null,"searchDate":null,"searchStartDate":null,"searchEndDate":null,"mode":null},"loginYn":"N","realtimeList":[{"stationId":"ST-4","stationImgFileName":"","stationName":"102. 망원역 1번출구 앞","stationLongitude":"126.91062927","stationLatitude":"37.55564880","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"2","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-5","stationImgFileName":"","stationName":"103. 망원역 2번출구 앞","stationLongitude":"126.91083527","stationLatitude":"37.55495071","rackTotCnt":"14","parkingBikeTotCnt":"0","parkingQRBikeCnt":"4","parkingELECBikeCnt":"2","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-6","stationImgFileName":"","stationName":"104. 합정역 1번출구 앞","stationLongitude":"126.91508484","stationLatitude":"37.55073929","rackTotCnt":"13","parkingBikeTotCnt":"0","parkingQRBikeCnt":"6","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-7","stationImgFileName":"","stationName":"105. 합정역 5번출구 앞","stationLongitude":"126.91482544","stationLatitude":"37.55000687","rackTotCnt":"5","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-8","stationImgFileName":"","stationName":"106. 합정역 7번출구 앞","stationLongitude":"126.91282654","stationLatitude":"37.54864502","rackTotCnt":"12","parkingBikeTotCnt":"0","parkingQRBikeCnt":"3","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-9","stationImgFileName":"","stationName":"107. 수협 연남동지점","stationLongitude":"126.91871643","stationLatitude":"37.55784607","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"7","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-10","stationImgFileName":"","stationName":"108. 서교동 사거리","stationLongitude":"126.91861725","stationLatitude":"37.55274582","rackTotCnt":"12","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-15","stationImgFileName":"","stationName":"111. 상수역 2번출구 앞","stationLongitude":"126.92353058","stationLatitude":"37.54787064","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"5","parkingELECBikeCnt":"4","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-18","stationImgFileName":"","stationName":"113. 홍대입구역 2번출구 앞","stationLongitude":"126.92382050","stationLatitude":"37.55743790","rackTotCnt":"28","parkingBikeTotCnt":"0","parkingQRBikeCnt":"32","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-20","stationImgFileName":"","stationName":"114. 홍대입구역 8번출구 앞","stationLongitude":"126.92442322","stationLatitude":"37.55706024","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"5","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-12","stationImgFileName":"","stationName":"115. 마스타 빌딩 앞","stationLongitude":"126.92711639","stationLatitude":"37.55893326","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"1","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-17","stationImgFileName":"","stationName":"117. 홍은사거리","stationLongitude":"126.94132996","stationLatitude":"37.59115982","rackTotCnt":"23","parkingBikeTotCnt":"0","parkingQRBikeCnt":"1","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-19","stationImgFileName":"","stationName":"118. 광흥창역 2번출구 앞","stationLongitude":"126.93176270","stationLatitude":"37.54773331","rackTotCnt":"9","parkingBikeTotCnt":"0","parkingQRBikeCnt":"1","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-21","stationImgFileName":"","stationName":"119. 서강나루 공원","stationLongitude":"126.93146515","stationLatitude":"37.54520798","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"18","parkingELECBikeCnt":"8","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-22","stationImgFileName":"","stationName":"120. 신수동 사거리","stationLongitude":"126.93411255","stationLatitude":"37.54524231","rackTotCnt":"5","parkingBikeTotCnt":"0","parkingQRBikeCnt":"4","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-23","stationImgFileName":"","stationName":"121. 마포소방서 앞","stationLongitude":"126.93317413","stationLatitude":"37.54976654","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"8","parkingELECBikeCnt":"4","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-24","stationImgFileName":"","stationName":"122. 신성기사식당 앞","stationLongitude":"126.93837738","stationLatitude":"37.54745865","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"5","parkingELECBikeCnt":"2","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-25","stationImgFileName":"","stationName":"123. 문화촌 공원","stationLongitude":"126.94738770","stationLatitude":"37.59432983","rackTotCnt":"20","parkingBikeTotCnt":"0","parkingQRBikeCnt":"25","parkingELECBikeCnt":"4","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-26","stationImgFileName":"","stationName":"124. 서강대 정문 건너편","stationLongitude":"126.93698883","stationLatitude":"37.55113983","rackTotCnt":"35","parkingBikeTotCnt":"0","parkingQRBikeCnt":"1","parkingELECBikeCnt":"1","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-28","stationImgFileName":"","stationName":"126. 서강대 후문 옆","stationLongitude":"126.94384766","stationLatitude":"37.55041122","rackTotCnt":"20","parkingBikeTotCnt":"0","parkingQRBikeCnt":"1","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-30","stationImgFileName":"","stationName":"128. 신촌역(2호선) 1번출구 옆","stationLongitude":"126.93634033","stationLatitude":"37.55549622","rackTotCnt":"19","parkingBikeTotCnt":"0","parkingQRBikeCnt":"4","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-31","stationImgFileName":"","stationName":"129. 신촌역(2호선) 6번출구 옆","stationLongitude":"126.93756866","stationLatitude":"37.55505371","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"9","parkingELECBikeCnt":"1","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-32","stationImgFileName":"","stationName":"130. 신촌역(2호선) 7번출구 앞","stationLongitude":"126.93626404","stationLatitude":"37.55504990","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"7","parkingELECBikeCnt":"1","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-33","stationImgFileName":"","stationName":"131. 증산2교","stationLongitude":"126.91110229","stationLatitude":"37.58417130","rackTotCnt":"20","parkingBikeTotCnt":"0","parkingQRBikeCnt":"3","parkingELECBikeCnt":"4","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-35","stationImgFileName":"","stationName":"133. 해담는다리","stationLongitude":"126.90899658","stationLatitude":"37.58203125","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"4","parkingELECBikeCnt":"5","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-36","stationImgFileName":"","stationName":"134. 연세로 명물길","stationLongitude":"126.93807983","stationLatitude":"37.55789185","rackTotCnt":"8","parkingBikeTotCnt":"0","parkingQRBikeCnt":"1","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-37","stationImgFileName":"","stationName":"135. 명물길 원형무대 앞","stationLongitude":"126.93984222","stationLatitude":"37.55922699","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"3","parkingELECBikeCnt":"1","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-39","stationImgFileName":"","stationName":"137. 신촌기차역입구 교차로","stationLongitude":"126.94318390","stationLatitude":"37.55681229","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"1","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-40","stationImgFileName":"","stationName":"138. 신촌동 제1공영주차장 앞","stationLongitude":"126.93452454","stationLatitude":"37.55917740","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"2","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-43","stationImgFileName":"","stationName":"139. 연세대 정문 건너편","stationLongitude":"126.93441772","stationLatitude":"37.55986404","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"1","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-41","stationImgFileName":"","stationName":"140. 이화여대 후문","stationLongitude":"126.94073486","stationLatitude":"37.56000900","rackTotCnt":"22","parkingBikeTotCnt":"0","parkingQRBikeCnt":"5","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-42","stationImgFileName":"","stationName":"141. 연대 대운동장 옆","stationLongitude":"126.93264771","stationLatitude":"37.56238174","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-200","stationImgFileName":"","stationName":"142. 아현역 4번출구 앞","stationLongitude":"126.95566559","stationLatitude":"37.55720139","rackTotCnt":"11","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"3","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-201","stationImgFileName":"","stationName":"143. 공덕역 2번출구","stationLongitude":"126.95008850","stationLatitude":"37.54464722","rackTotCnt":"8","parkingBikeTotCnt":"0","parkingQRBikeCnt":"12","parkingELECBikeCnt":"1","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-203","stationImgFileName":"","stationName":"145. 공덕역 5번출구","stationLongitude":"126.95163727","stationLatitude":"37.54425049","rackTotCnt":"9","parkingBikeTotCnt":"0","parkingQRBikeCnt":"20","parkingELECBikeCnt":"4","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-204","stationImgFileName":"","stationName":"146. 마포역 2번출구 뒤","stationLongitude":"126.94582367","stationLatitude":"37.53993607","rackTotCnt":"12","parkingBikeTotCnt":"0","parkingQRBikeCnt":"10","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-205","stationImgFileName":"","stationName":"147. 마포역 4번출구 뒤","stationLongitude":"126.94591522","stationLatitude":"37.53927231","rackTotCnt":"5","parkingBikeTotCnt":"0","parkingQRBikeCnt":"3","parkingELECBikeCnt":"7","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-206","stationImgFileName":"","stationName":"148. 용강동 주민센터 앞","stationLongitude":"126.94302368","stationLatitude":"37.54234695","rackTotCnt":"11","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"2","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-207","stationImgFileName":"","stationName":"150. 서강대역 2번출구 앞","stationLongitude":"126.93434143","stationLatitude":"37.55295563","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"2","parkingELECBikeCnt":"3","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-210","stationImgFileName":"","stationName":"153. 성산2교 사거리","stationLongitude":"126.91261292","stationLatitude":"37.56469727","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"1","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-211","stationImgFileName":"","stationName":"154. 마포구청역 ","stationLongitude":"126.90549469","stationLatitude":"37.56090927","rackTotCnt":"11","parkingBikeTotCnt":"0","parkingQRBikeCnt":"16","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-212","stationImgFileName":"","stationName":"155. 가좌역1 번출구 앞","stationLongitude":"126.91504669","stationLatitude":"37.56829453","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"25","parkingELECBikeCnt":"3","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-213","stationImgFileName":"","stationName":"156. 서울서부지방법원 앞","stationLongitude":"126.95491791","stationLatitude":"37.54933167","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"13","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-214","stationImgFileName":"","stationName":"157. 애오개역 4번출구 앞","stationLongitude":"126.95668793","stationLatitude":"37.55300140","rackTotCnt":"12","parkingBikeTotCnt":"0","parkingQRBikeCnt":"1","parkingELECBikeCnt":"4","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-216","stationImgFileName":"","stationName":"159. 이대역 4번 출구","stationLongitude":"126.94634247","stationLatitude":"37.55695343","rackTotCnt":"5","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-217","stationImgFileName":"","stationName":"160. 북아현동 가구거리","stationLongitude":"126.95938110","stationLatitude":"37.55754852","rackTotCnt":"13","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-218","stationImgFileName":"","stationName":"161. 무악재역1번 출구","stationLongitude":"126.95064545","stationLatitude":"37.58224487","rackTotCnt":"8","parkingBikeTotCnt":"0","parkingQRBikeCnt":"3","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-219","stationImgFileName":"","stationName":"162. 봉원고가차도 밑","stationLongitude":"126.94667053","stationLatitude":"37.56626129","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-220","stationImgFileName":"","stationName":"163. 명지전문대학교 정문 앞","stationLongitude":"126.92496490","stationLatitude":"37.58369827","rackTotCnt":"6","parkingBikeTotCnt":"0","parkingQRBikeCnt":"2","parkingELECBikeCnt":"1","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-221","stationImgFileName":"","stationName":"164. 북가좌1동 주민센터 ","stationLongitude":"126.91004944","stationLatitude":"37.57447815","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"1","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-222","stationImgFileName":"","stationName":"165. 중앙근린공원","stationLongitude":"126.91394043","stationLatitude":"37.57513809","rackTotCnt":"20","parkingBikeTotCnt":"0","parkingQRBikeCnt":"17","parkingELECBikeCnt":"7","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-223","stationImgFileName":"","stationName":"166. 가재울 초등학교","stationLongitude":"126.91923523","stationLatitude":"37.57381821","rackTotCnt":"20","parkingBikeTotCnt":"0","parkingQRBikeCnt":"13","parkingELECBikeCnt":"4","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-224","stationImgFileName":"","stationName":"167. 연가초등학교 옆","stationLongitude":"126.91712952","stationLatitude":"37.57946014","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"4","parkingELECBikeCnt":"2","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-226","stationImgFileName":"","stationName":"169. 북가좌 삼거리","stationLongitude":"126.90779877","stationLatitude":"37.57300186","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"4","parkingELECBikeCnt":"1","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-227","stationImgFileName":"","stationName":"170. DMC파크뷰자이아파트 302동 앞","stationLongitude":"126.92244720","stationLatitude":"37.57311249","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"17","parkingELECBikeCnt":"8","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-228","stationImgFileName":"","stationName":"171. 임광빌딩 앞","stationLongitude":"126.96727753","stationLatitude":"37.56472397","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"2","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-230","stationImgFileName":"","stationName":"173. 서대문역 8번출구 앞","stationLongitude":"126.96614838","stationLatitude":"37.56477737","rackTotCnt":"8","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"5","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-231","stationImgFileName":"","stationName":"175. 홍연2교옆","stationLongitude":"126.93088531","stationLatitude":"37.57806778","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"5","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-555","stationImgFileName":"","stationName":"176. 명지대학교 도서관","stationLongitude":"126.92402649","stationLatitude":"37.58109665","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"26","parkingELECBikeCnt":"3","stationSeCd":"RAK_001","mode":null},{"stationId":"ST-345","stationImgFileName":"","stationName":"177. 북가좌 초등학교","stationLongitude":"126.90965271","stationLatitude":"37.57763672","rackTotCnt":"8","parkingBikeTotCnt":"0","parkingQRBikeCnt":"15","parkingELECBikeCnt":"5","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-349","stationImgFileName":"","stationName":"178. 증산3교 앞","stationLongitude":"126.90634918","stationLatitude":"37.57987595","rackTotCnt":"9","parkingBikeTotCnt":"0","parkingQRBikeCnt":"4","parkingELECBikeCnt":"3","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-232","stationImgFileName":"","stationName":"179. 가좌역 4번출구 앞","stationLongitude":"126.91529846","stationLatitude":"37.56877518","rackTotCnt":"14","parkingBikeTotCnt":"0","parkingQRBikeCnt":"27","parkingELECBikeCnt":"2","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-233","stationImgFileName":"","stationName":"180. 충정로역 7번출구 아래","stationLongitude":"126.96246338","stationLatitude":"37.55996704","rackTotCnt":"10","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-339","stationImgFileName":"","stationName":"181. 망원초록길 입구","stationLongitude":"126.90267181","stationLatitude":"37.55134201","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"2","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-340","stationImgFileName":"","stationName":"182. 망원2빗물펌프장 앞","stationLongitude":"126.90306091","stationLatitude":"37.55136490","rackTotCnt":"9","parkingBikeTotCnt":"0","parkingQRBikeCnt":"0","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-341","stationImgFileName":"","stationName":"183. 하늘채코오롱아파트 건너편","stationLongitude":"126.91932678","stationLatitude":"37.56538773","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"15","parkingELECBikeCnt":"9","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-342","stationImgFileName":"","stationName":"184.망원우체국사거리 인근","stationLongitude":"126.90775299","stationLatitude":"37.55894852","rackTotCnt":"8","parkingBikeTotCnt":"0","parkingQRBikeCnt":"10","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-343","stationImgFileName":"","stationName":"185. 마포 신수공원 앞","stationLongitude":"126.93429565","stationLatitude":"37.54254532","rackTotCnt":"15","parkingBikeTotCnt":"0","parkingQRBikeCnt":"1","parkingELECBikeCnt":"0","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-344","stationImgFileName":"","stationName":"186. 월드컵공원","stationLongitude":"126.89820862","stationLatitude":"37.56396484","rackTotCnt":"40","parkingBikeTotCnt":"0","parkingQRBikeCnt":"9","parkingELECBikeCnt":"22","stationSeCd":"RAK_002","mode":null},{"stationId":"ST-346","stationImgFileName":"","stationName":"188. 홍은동 정원여중 입구","stationLongitude":"126.93512726","stationLatitude":"37.58638763","rackTotCnt":"9"

따릉이 서버가 응답하는 json 형태의 문자열을 파이썬에서 사용하기 위해서 딕셔너리나 리스트 타입으로 변환한다.

In [4]:
# json 모듈의 loads() 메소드를 사용한다.
# bike = json.loads(response.text)
# requests 모듈의 응답 객체에서 json() 메소드를 사용한다.
bike = response.json()
# print(type(bike)) # <class 'dict'>
# print(bike)
print(bike.keys())

dict_keys(['stationImgPath', 'appUserSessionVO', 'loginYn', 'realtimeList', 'sessionId', 'stationVO', 'checkResult'])

딕셔너리 타입으로 변환된 데이터에서 'realtimeList'라는 key에 할당된 정보를 얻어온다. => 따릉이 스테이션 정보

In [5]:
# print(bike.get('realtimeList'))
print(len(bike['realtimeList']))
bike['realtimeList']

2735

[{'stationId': 'ST-4',
  'stationImgFileName': '',
  'stationName': '102. 망원역 1번출구 앞',
  'stationLongitude': '126.91062927',
  'stationLatitude': '37.55564880',
  'rackTotCnt': '15',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '2',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-5',
  'stationImgFileName': '',
  'stationName': '103. 망원역 2번출구 앞',
  'stationLongitude': '126.91083527',
  'stationLatitude': '37.55495071',
  'rackTotCnt': '14',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '4',
  'parkingELECBikeCnt': '2',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-6',
  'stationImgFileName': '',
  'stationName': '104. 합정역 1번출구 앞',
  'stationLongitude': '126.91508484',
  'stationLatitude': '37.55073929',
  'rackTotCnt': '13',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '6',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-7',
  'stationImgFileName': '',
  'stationName': '105. 합정역 5번출구 앞',
  'stationLongitude': '126.91482544',
  'stationLatitude': '37.55000687',
  'rackTotCnt': '5',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-8',
  'stationImgFileName': '',
  'stationName': '106. 합정역 7번출구 앞',
  'stationLongitude': '126.91282654',
  'stationLatitude': '37.54864502',
  'rackTotCnt': '12',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '3',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-9',
  'stationImgFileName': '',
  'stationName': '107. 수협 연남동지점',
  'stationLongitude': '126.91871643',
  'stationLatitude': '37.55784607',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '7',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-10',
  'stationImgFileName': '',
  'stationName': '108. 서교동 사거리',
  'stationLongitude': '126.91861725',
  'stationLatitude': '37.55274582',
  'rackTotCnt': '12',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-15',
  'stationImgFileName': '',
  'stationName': '111. 상수역 2번출구 앞',
  'stationLongitude': '126.92353058',
  'stationLatitude': '37.54787064',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '5',
  'parkingELECBikeCnt': '4',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-18',
  'stationImgFileName': '',
  'stationName': '113. 홍대입구역 2번출구 앞',
  'stationLongitude': '126.92382050',
  'stationLatitude': '37.55743790',
  'rackTotCnt': '28',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '32',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-20',
  'stationImgFileName': '',
  'stationName': '114. 홍대입구역 8번출구 앞',
  'stationLongitude': '126.92442322',
  'stationLatitude': '37.55706024',
  'rackTotCnt': '15',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '5',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-12',
  'stationImgFileName': '',
  'stationName': '115. 마스타 빌딩 앞',
  'stationLongitude': '126.92711639',
  'stationLatitude': '37.55893326',
  'rackTotCnt': '15',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '1',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-17',
  'stationImgFileName': '',
  'stationName': '117. 홍은사거리',
  'stationLongitude': '126.94132996',
  'stationLatitude': '37.59115982',
  'rackTotCnt': '23',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '1',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-19',
  'stationImgFileName': '',
  'stationName': '118. 광흥창역 2번출구 앞',
  'stationLongitude': '126.93176270',
  'stationLatitude': '37.54773331',
  'rackTotCnt': '9',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '1',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-21',
  'stationImgFileName': '',
  'stationName': '119. 서강나루 공원',
  'stationLongitude': '126.93146515',
  'stationLatitude': '37.54520798',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '18',
  'parkingELECBikeCnt': '8',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-22',
  'stationImgFileName': '',
  'stationName': '120. 신수동 사거리',
  'stationLongitude': '126.93411255',
  'stationLatitude': '37.54524231',
  'rackTotCnt': '5',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '4',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-23',
  'stationImgFileName': '',
  'stationName': '121. 마포소방서 앞',
  'stationLongitude': '126.93317413',
  'stationLatitude': '37.54976654',
  'rackTotCnt': '15',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '8',
  'parkingELECBikeCnt': '4',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-24',
  'stationImgFileName': '',
  'stationName': '122. 신성기사식당 앞',
  'stationLongitude': '126.93837738',
  'stationLatitude': '37.54745865',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '5',
  'parkingELECBikeCnt': '2',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-25',
  'stationImgFileName': '',
  'stationName': '123. 문화촌 공원',
  'stationLongitude': '126.94738770',
  'stationLatitude': '37.59432983',
  'rackTotCnt': '20',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '25',
  'parkingELECBikeCnt': '4',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-26',
  'stationImgFileName': '',
  'stationName': '124. 서강대 정문 건너편',
  'stationLongitude': '126.93698883',
  'stationLatitude': '37.55113983',
  'rackTotCnt': '35',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '1',
  'parkingELECBikeCnt': '1',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-28',
  'stationImgFileName': '',
  'stationName': '126. 서강대 후문 옆',
  'stationLongitude': '126.94384766',
  'stationLatitude': '37.55041122',
  'rackTotCnt': '20',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '1',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-30',
  'stationImgFileName': '',
  'stationName': '128. 신촌역(2호선) 1번출구 옆',
  'stationLongitude': '126.93634033',
  'stationLatitude': '37.55549622',
  'rackTotCnt': '19',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '4',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-31',
  'stationImgFileName': '',
  'stationName': '129. 신촌역(2호선) 6번출구 옆',
  'stationLongitude': '126.93756866',
  'stationLatitude': '37.55505371',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '9',
  'parkingELECBikeCnt': '1',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-32',
  'stationImgFileName': '',
  'stationName': '130. 신촌역(2호선) 7번출구 앞',
  'stationLongitude': '126.93626404',
  'stationLatitude': '37.55504990',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '7',
  'parkingELECBikeCnt': '1',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-33',
  'stationImgFileName': '',
  'stationName': '131. 증산2교',
  'stationLongitude': '126.91110229',
  'stationLatitude': '37.58417130',
  'rackTotCnt': '20',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '3',
  'parkingELECBikeCnt': '4',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-35',
  'stationImgFileName': '',
  'stationName': '133. 해담는다리',
  'stationLongitude': '126.90899658',
  'stationLatitude': '37.58203125',
  'rackTotCnt': '15',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '4',
  'parkingELECBikeCnt': '5',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-36',
  'stationImgFileName': '',
  'stationName': '134. 연세로 명물길',
  'stationLongitude': '126.93807983',
  'stationLatitude': '37.55789185',
  'rackTotCnt': '8',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '1',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-37',
  'stationImgFileName': '',
  'stationName': '135. 명물길 원형무대 앞',
  'stationLongitude': '126.93984222',
  'stationLatitude': '37.55922699',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '3',
  'parkingELECBikeCnt': '1',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-39',
  'stationImgFileName': '',
  'stationName': '137. 신촌기차역입구 교차로',
  'stationLongitude': '126.94318390',
  'stationLatitude': '37.55681229',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '1',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-40',
  'stationImgFileName': '',
  'stationName': '138. 신촌동 제1공영주차장 앞',
  'stationLongitude': '126.93452454',
  'stationLatitude': '37.55917740',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '2',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-43',
  'stationImgFileName': '',
  'stationName': '139. 연세대 정문 건너편',
  'stationLongitude': '126.93441772',
  'stationLatitude': '37.55986404',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '1',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-41',
  'stationImgFileName': '',
  'stationName': '140. 이화여대 후문',
  'stationLongitude': '126.94073486',
  'stationLatitude': '37.56000900',
  'rackTotCnt': '22',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '5',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-42',
  'stationImgFileName': '',
  'stationName': '141. 연대 대운동장 옆',
  'stationLongitude': '126.93264771',
  'stationLatitude': '37.56238174',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-200',
  'stationImgFileName': '',
  'stationName': '142. 아현역 4번출구 앞',
  'stationLongitude': '126.95566559',
  'stationLatitude': '37.55720139',
  'rackTotCnt': '11',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '3',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-201',
  'stationImgFileName': '',
  'stationName': '143. 공덕역 2번출구',
  'stationLongitude': '126.95008850',
  'stationLatitude': '37.54464722',
  'rackTotCnt': '8',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '12',
  'parkingELECBikeCnt': '1',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-203',
  'stationImgFileName': '',
  'stationName': '145. 공덕역 5번출구',
  'stationLongitude': '126.95163727',
  'stationLatitude': '37.54425049',
  'rackTotCnt': '9',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '20',
  'parkingELECBikeCnt': '4',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-204',
  'stationImgFileName': '',
  'stationName': '146. 마포역 2번출구 뒤',
  'stationLongitude': '126.94582367',
  'stationLatitude': '37.53993607',
  'rackTotCnt': '12',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '10',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-205',
  'stationImgFileName': '',
  'stationName': '147. 마포역 4번출구 뒤',
  'stationLongitude': '126.94591522',
  'stationLatitude': '37.53927231',
  'rackTotCnt': '5',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '3',
  'parkingELECBikeCnt': '7',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-206',
  'stationImgFileName': '',
  'stationName': '148. 용강동 주민센터 앞',
  'stationLongitude': '126.94302368',
  'stationLatitude': '37.54234695',
  'rackTotCnt': '11',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '2',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-207',
  'stationImgFileName': '',
  'stationName': '150. 서강대역 2번출구 앞',
  'stationLongitude': '126.93434143',
  'stationLatitude': '37.55295563',
  'rackTotCnt': '15',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '2',
  'parkingELECBikeCnt': '3',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-210',
  'stationImgFileName': '',
  'stationName': '153. 성산2교 사거리',
  'stationLongitude': '126.91261292',
  'stationLatitude': '37.56469727',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '1',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-211',
  'stationImgFileName': '',
  'stationName': '154. 마포구청역 ',
  'stationLongitude': '126.90549469',
  'stationLatitude': '37.56090927',
  'rackTotCnt': '11',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '16',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-212',
  'stationImgFileName': '',
  'stationName': '155. 가좌역1 번출구 앞',
  'stationLongitude': '126.91504669',
  'stationLatitude': '37.56829453',
  'rackTotCnt': '15',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '25',
  'parkingELECBikeCnt': '3',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-213',
  'stationImgFileName': '',
  'stationName': '156. 서울서부지방법원 앞',
  'stationLongitude': '126.95491791',
  'stationLatitude': '37.54933167',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '13',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-214',
  'stationImgFileName': '',
  'stationName': '157. 애오개역 4번출구 앞',
  'stationLongitude': '126.95668793',
  'stationLatitude': '37.55300140',
  'rackTotCnt': '12',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '1',
  'parkingELECBikeCnt': '4',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-216',
  'stationImgFileName': '',
  'stationName': '159. 이대역 4번 출구',
  'stationLongitude': '126.94634247',
  'stationLatitude': '37.55695343',
  'rackTotCnt': '5',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-217',
  'stationImgFileName': '',
  'stationName': '160. 북아현동 가구거리',
  'stationLongitude': '126.95938110',
  'stationLatitude': '37.55754852',
  'rackTotCnt': '13',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-218',
  'stationImgFileName': '',
  'stationName': '161. 무악재역1번 출구',
  'stationLongitude': '126.95064545',
  'stationLatitude': '37.58224487',
  'rackTotCnt': '8',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '3',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-219',
  'stationImgFileName': '',
  'stationName': '162. 봉원고가차도 밑',
  'stationLongitude': '126.94667053',
  'stationLatitude': '37.56626129',
  'rackTotCnt': '15',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-220',
  'stationImgFileName': '',
  'stationName': '163. 명지전문대학교 정문 앞',
  'stationLongitude': '126.92496490',
  'stationLatitude': '37.58369827',
  'rackTotCnt': '6',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '2',
  'parkingELECBikeCnt': '1',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-221',
  'stationImgFileName': '',
  'stationName': '164. 북가좌1동 주민센터 ',
  'stationLongitude': '126.91004944',
  'stationLatitude': '37.57447815',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '1',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-222',
  'stationImgFileName': '',
  'stationName': '165. 중앙근린공원',
  'stationLongitude': '126.91394043',
  'stationLatitude': '37.57513809',
  'rackTotCnt': '20',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '17',
  'parkingELECBikeCnt': '7',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-223',
  'stationImgFileName': '',
  'stationName': '166. 가재울 초등학교',
  'stationLongitude': '126.91923523',
  'stationLatitude': '37.57381821',
  'rackTotCnt': '20',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '13',
  'parkingELECBikeCnt': '4',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-224',
  'stationImgFileName': '',
  'stationName': '167. 연가초등학교 옆',
  'stationLongitude': '126.91712952',
  'stationLatitude': '37.57946014',
  'rackTotCnt': '15',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '4',
  'parkingELECBikeCnt': '2',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-226',
  'stationImgFileName': '',
  'stationName': '169. 북가좌 삼거리',
  'stationLongitude': '126.90779877',
  'stationLatitude': '37.57300186',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '4',
  'parkingELECBikeCnt': '1',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-227',
  'stationImgFileName': '',
  'stationName': '170. DMC파크뷰자이아파트 302동 앞',
  'stationLongitude': '126.92244720',
  'stationLatitude': '37.57311249',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '17',
  'parkingELECBikeCnt': '8',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-228',
  'stationImgFileName': '',
  'stationName': '171. 임광빌딩 앞',
  'stationLongitude': '126.96727753',
  'stationLatitude': '37.56472397',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '2',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-230',
  'stationImgFileName': '',
  'stationName': '173. 서대문역 8번출구 앞',
  'stationLongitude': '126.96614838',
  'stationLatitude': '37.56477737',
  'rackTotCnt': '8',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '5',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-231',
  'stationImgFileName': '',
  'stationName': '175. 홍연2교옆',
  'stationLongitude': '126.93088531',
  'stationLatitude': '37.57806778',
  'rackTotCnt': '15',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '5',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-555',
  'stationImgFileName': '',
  'stationName': '176. 명지대학교 도서관',
  'stationLongitude': '126.92402649',
  'stationLatitude': '37.58109665',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '26',
  'parkingELECBikeCnt': '3',
  'stationSeCd': 'RAK_001',
  'mode': None},
 {'stationId': 'ST-345',
  'stationImgFileName': '',
  'stationName': '177. 북가좌 초등학교',
  'stationLongitude': '126.90965271',
  'stationLatitude': '37.57763672',
  'rackTotCnt': '8',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '15',
  'parkingELECBikeCnt': '5',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-349',
  'stationImgFileName': '',
  'stationName': '178. 증산3교 앞',
  'stationLongitude': '126.90634918',
  'stationLatitude': '37.57987595',
  'rackTotCnt': '9',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '4',
  'parkingELECBikeCnt': '3',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-232',
  'stationImgFileName': '',
  'stationName': '179. 가좌역 4번출구 앞',
  'stationLongitude': '126.91529846',
  'stationLatitude': '37.56877518',
  'rackTotCnt': '14',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '27',
  'parkingELECBikeCnt': '2',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-233',
  'stationImgFileName': '',
  'stationName': '180. 충정로역 7번출구 아래',
  'stationLongitude': '126.96246338',
  'stationLatitude': '37.55996704',
  'rackTotCnt': '10',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '0',
  'stationSeCd': 'RAK_002',
  'mode': None},
 {'stationId': 'ST-339',
  'stationImgFileName': '',
  'stationName': '181. 망원초록길 입구',
  'stationLongitude': '126.90267181',
  'stationLatitude': '37.55134201',
  'rackTotCnt': '15',
  'parkingBikeTotCnt': '0',
  'parkingQRBikeCnt': '0',
  'parkingELECBikeCnt': '2',
  'stationSeCd': 'RAK_002',

json_normalize() 함수를 이용해서 따릉이 스테이션 정보를 판다스 데이터프레임으로 만든다.  
json_normalize(딕셔너리, 데이터프레임으로 만들려는 딕셔너리의 key)

In [6]:
bike_df = json_normalize(bike, 'realtimeList')
bike_df

,stationId,stationImgFileName,stationName,stationLongitude,stationLatitude,rackTotCnt,parkingBikeTotCnt,parkingQRBikeCnt,parkingELECBikeCnt,stationSeCd,mode
0,ST-4,,102. 망원역 1번출구 앞,126.91062927,37.55564880,15,0,2,0,RAK_002,None
1,ST-5,,103. 망원역 2번출구 앞,126.91083527,37.55495071,14,0,4,2,RAK_002,None
2,ST-6,,104. 합정역 1번출구 앞,126.91508484,37.55073929,13,0,6,0,RAK_002,None
3,ST-7,,105. 합정역 5번출구 앞,126.91482544,37.55000687,5,0,0,0,RAK_002,None
4,ST-8,,106. 합정역 7번출구 앞,126.91282654,37.54864502,12,0,3,0,RAK_002,None
...,...,...,...,...,...,...,...,...,...,...,...
2730,ST-3418,,6185.가양나들목,126.84345245,37.57341003,8,0,5,2,RAK_002,None
2731,ST-3415,,6187.마곡119안전센터 맞은편,126.82072449,37.55534744,12,0,2,4,RAK_002,None
2732,ST-3419,,6188.금호아파트,126.86475372,37.55611038,17,0,38,7,RAK_002,None
2733,ST-3424,,6189.데시앙플렉스 지식산업센터,126.84830475,37.56448364,11,0,2,0,RAK_002,None
2734,ST-3421,,6190.마곡광장(마곡나루역 6번출구),126.82738495,37.56614685,10,0,12,0,RAK_002,None

In [7]:
bike_df.columns

Index(['stationId', 'stationImgFileName', 'stationName', 'stationLongitude',
       'stationLatitude', 'rackTotCnt', 'parkingBikeTotCnt',
       'parkingQRBikeCnt', 'parkingELECBikeCnt', 'stationSeCd', 'mode'],
      dtype='str')

bike_df 데이터프레임에서 아래의 컬럼만 사용하기위해 불필요한 컬럼은 제거한다.

stationId: 대여소 id  
stationName': 대여소 이름  
stationLongitude': 대여소 경도  
stationLatitude': 대여소 위도  
rackTotCnt': 대여소에 주차 가능한 자전거 대수  
parkingBikeTotCnt': 대여소에 주차된 LCD형 따릉이 대수 => 사용하지 않음  
parkingQRBikeCnt': 대여소에 주차된 QR형 따릉이 대수 => 일반 따릉이  
parkingELECBikeCnt': 대여소에 주차된 새싹 따릉이 대수

In [8]:
# bike = bike_df.drop(columns=['stationImgFileName', 'stationSeCd', 'mode'])
bike = bike_df[['stationId', 'stationName', 'stationLongitude', 'stationLatitude', 'rackTotCnt', 'parkingBikeTotCnt','parkingQRBikeCnt', 'parkingELECBikeCnt']]
del bike_df
bike

,stationId,stationName,stationLongitude,stationLatitude,rackTotCnt,parkingBikeTotCnt,parkingQRBikeCnt,parkingELECBikeCnt
0,ST-4,102. 망원역 1번출구 앞,126.91062927,37.55564880,15,0,2,0
1,ST-5,103. 망원역 2번출구 앞,126.91083527,37.55495071,14,0,4,2
2,ST-6,104. 합정역 1번출구 앞,126.91508484,37.55073929,13,0,6,0
3,ST-7,105. 합정역 5번출구 앞,126.91482544,37.55000687,5,0,0,0
4,ST-8,106. 합정역 7번출구 앞,126.91282654,37.54864502,12,0,3,0
...,...,...,...,...,...,...,...,...
2730,ST-3418,6185.가양나들목,126.84345245,37.57341003,8,0,5,2
2731,ST-3415,6187.마곡119안전센터 맞은편,126.82072449,37.55534744,12,0,2,4
2732,ST-3419,6188.금호아파트,126.86475372,37.55611038,17,0,38,7
2733,ST-3424,6189.데시앙플렉스 지식산업센터,126.84830475,37.56448364,11,0,2,0
2734,ST-3421,6190.마곡광장(마곡나루역 6번출구),126.82738495,37.56614685,10,0,12,0

위도, 경도, 전체 자전거 주차 대수를 기억할 파생 변수 등을 고려해서 데이터 타입을 변경한다.

In [9]:
# bike.dtypes
bike.info()

<class 'pandas.DataFrame'>
RangeIndex: 2735 entries, 0 to 2734
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stationId           2735 non-null   str
 1   stationName         2735 non-null   str
 2   stationLongitude    2735 non-null   str
 3   stationLatitude     2735 non-null   str
 4   rackTotCnt          2735 non-null   str
 5   parkingBikeTotCnt   2735 non-null   str
 6   parkingQRBikeCnt    2735 non-null   str
 7   parkingELECBikeCnt  2735 non-null   str
dtypes: str(8)
memory usage: 171.1 KB

In [10]:
bike['stationLongitude'] = bike.stationLongitude.astype(float)
bike['stationLatitude'] = bike.stationLatitude.astype(float)
bike['parkingBikeTotCnt'] = bike.parkingBikeTotCnt.astype(int)
bike['parkingQRBikeCnt'] = bike.parkingQRBikeCnt.astype(int)
bike['parkingELECBikeCnt'] = bike.parkingELECBikeCnt.astype(int)
# 따릉이 스테이션에 현재 주차된 자전거 대수를 기억하는 파생 변수를 만든다.
bike['parking'] = bike['parkingBikeTotCnt'] + bike['parkingQRBikeCnt'] + bike['parkingELECBikeCnt']
bike.head()

,stationId,stationName,stationLongitude,stationLatitude,rackTotCnt,parkingBikeTotCnt,parkingQRBikeCnt,parkingELECBikeCnt,parking
0,ST-4,102. 망원역 1번출구 앞,126.910629,37.555649,15,0,2,0,2
1,ST-5,103. 망원역 2번출구 앞,126.910835,37.554951,14,0,4,2,6
2,ST-6,104. 합정역 1번출구 앞,126.915085,37.550739,13,0,6,0,6
3,ST-7,105. 합정역 5번출구 앞,126.914825,37.550007,5,0,0,0,0
4,ST-8,106. 합정역 7번출구 앞,126.912827,37.548645,12,0,3,0,3

In [11]:
bike.to_csv('./data/bike.csv', index=False)
bike.dtypes

stationId                 str
stationName               str
stationLongitude      float64
stationLatitude       float64
rackTotCnt                str
parkingBikeTotCnt       int64
parkingQRBikeCnt        int64
parkingELECBikeCnt      int64
parking                 int64
dtype: object

서울시 전체 따릉이 스테이션 시각화

In [12]:
bike_map = folium.Map(location=[bike.stationLatitude.mean(), bike.stationLongitude.mean()], zoom_start=12)

for i in bike.index[::10]:
    # 따릉이 스테이션 이름앞에 '숫자.'이 있는 경우와 없는 경우를 대비해서 try ~ except를 사용해서 스테이션 이름을 처리한다.
    try:
        stationName = bike.loc[i, 'stationName'].split('.')[1].strip()
    except:
        stationName = bike.loc[i, 'stationName'].split('.')[0].strip()
    # print() 함수에서 '\n'을 사용하면 줄이 변경되지만 folium의 popup은 내부적으로 HTML로 렌더링되기 때문에 '\n'가 무시된다.
    # folium의 popup을 사용할때 줄을 바꾸려면 '\n' 대신에 HTML의 줄바꿈 태그 '<br>'을 사용해야 한다.
    string = '스테이션 이름: {}<br>현재 주차된 자전거 대수: {}대'.format(
        stationName,
        bike.loc[i, 'parking']
    )
    popup = folium.Popup(string, max_width=300)
    
    folium.Marker(
        location=[bike.loc[i, 'stationLatitude'], bike.loc[i, 'stationLongitude']], 
        popup=popup,
    ).add_to(bike_map)

bike_map.save('./output/bike_map.html')
bike_map

GeoCoding

지오코딩: 주소로 위도, 경도 정보 얻기, 역지오코딩: 위도, 경도로 주소 정보 얻기

지오코딩을 사용하기 위해서 라이브러리를 설치하고 import 한다.

GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%EC%84%9C%EC%9A%B8%EC%8B%9C+%EC%A2%85%EB%A1%9C%EA%B5%AC+%EA%B4%80%EC%B2%A0%EB%8F%99&format=json&limit=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))  
위와 같은 에러가 발생되면 아래의 코드를 추가하고 실행한다.

import certifi  
import ssl  
import geopy.geocoders  

ctx = ssl.create_default_context(cafile=certifi.where())  
geopy.geocoders.options.default_ssl_context = ctx

In [13]:
# !pip install geopy
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderRateLimited

# GeocoderRateLimited: Non-successful status code 429 에러 방지를 위해서 Nominatim 객체를 함수가 실행될때마다 생성하지 않고 미리 생성한다.
# user_agent 속성값을 다른 사용자와 겹치지 않게 나만의 고유한 이름으로 변경한다.
geocoder = Nominatim(user_agent='my_unique_geocode_id_mkvryu_20260709', timeout=None)

지오코딩(주소를 인수로 넘겨받아 위도, 경도를 리턴하는) 함수를 만든다.

In [14]:
def geocoding(address):
    # Nominatim() 객체가 함수가 실행될때마다 생성된다.
    # geocoder = Nominatim(user_agent='South Korea', timeout=None)
    geo = geocoder.geocode(address)
    return {'위도': geo.latitude, '경도': geo.longitude}

address = geocoding('서울시 종로구 관철동')  
print(address)  
address = geocoding('서울시 강남구 역삼동')  
print(address)

역지오코딩(위도, 경도를 인수로 넘겨받아 주소를 리턴하는) 함수를 만든다.

In [45]:
def geocoding_reverse(lat_lon):
    # Nominatim() 객체가 함수가 실행될때마다 생성된다.
    # geocoder = Nominatim(user_agent='South Korea', timeout=None)
    while True:
        try:
            time.sleep(1.5)
            return geocoder.reverse(lat_lon)
        except GeocoderRateLimited:
            print("서버 차단 감지! 20초간 대기 후 재시도합니다...")
            time.sleep(20)
        except:
            print(f"기타 에러:")
            return None
        finally:
            pass

address = geocoding_reverse('37.5687846,126.9857059')  
print(type(address))  
print(address)  
address = str(address).split(', ')  
print(type(address))  
print(address)  
print(address[-3], address[-4], address[-5])  
print('=' * 100)  

address = geocoding_reverse('37.49988,127.03856')  
address = str(address).split(', ')  
print(address)  
print(address[-3], address[-4], address[-5])

역지오코딩을 통해서 위도와 경도로 얻어진 구(goo)와 동(dong)을 파생 변수로 추가한다.

In [22]:
bike['goo'] = np.nan
bike['dong'] = np.nan
bike['goo'] = bike['goo'].astype(str)
bike['dong'] = bike['dong'].astype(str)
bike

,stationId,stationName,stationLongitude,stationLatitude,rackTotCnt,parkingBikeTotCnt,parkingQRBikeCnt,parkingELECBikeCnt,parking,goo,dong
0,ST-4,102. 망원역 1번출구 앞,126.910629,37.555649,15,0,2,0,2,NaN,NaN
1,ST-5,103. 망원역 2번출구 앞,126.910835,37.554951,14,0,4,2,6,NaN,NaN
2,ST-6,104. 합정역 1번출구 앞,126.915085,37.550739,13,0,6,0,6,NaN,NaN
3,ST-7,105. 합정역 5번출구 앞,126.914825,37.550007,5,0,0,0,0,NaN,NaN
4,ST-8,106. 합정역 7번출구 앞,126.912827,37.548645,12,0,3,0,3,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2730,ST-3418,6185.가양나들목,126.843452,37.573410,8,0,5,2,7,NaN,NaN
2731,ST-3415,6187.마곡119안전센터 맞은편,126.820724,37.555347,12,0,2,4,6,NaN,NaN
2732,ST-3419,6188.금호아파트,126.864754,37.556110,17,0,38,7,45,NaN,NaN
2733,ST-3424,6189.데시앙플렉스 지식산업센터,126.848305,37.564484,11,0,2,0,2,NaN,NaN
2734,ST-3421,6190.마곡광장(마곡나루역 6번출구),126.827385,37.566147,10,0,12,0,12,NaN,NaN

In [28]:
'''
for i in range(bike.shape[0])[:]:
    lat_lon = f"{bike.loc[i, 'stationLatitude']},{bike.loc[i, 'stationLongitude']}"
    # print(lat_lon)
    address = geocoding_reverse(lat_lon)
    address = str(address).split(', ')
    print(address[-3], address[-4], address[-5])
    
    try:
        bike.loc[i, 'goo'] = address[-4]
    except:
        print('{}번째 인덱스 따릉이 스테이션의 -4번째 주소 없음'.format(i))
        
    try:
        bike.loc[i, 'dong'] = address[-5]
    except:
        print('{}번째 인덱스 따릉이 스테이션의 -5번째 주소 없음'.format(i))
        
    if (i + 1) % 20 == 0:
        print('================', i + 1, '================')
'''
pass

In [65]:
# bike.to_csv('./data/bike_20260709.csv', index=False)
bike = pd.read_csv('./data/bike_20260709.csv') # cp949 어쩌구 에러가 발생되면 encoding='cp949'를 추가한다.
bike

,stationId,stationName,stationLongitude,stationLatitude,rackTotCnt,parkingBikeTotCnt,parkingQRBikeCnt,parkingELECBikeCnt,parking,goo,dong
0,ST-4,102. 망원역 1번출구 앞,126.910629,37.555649,15,0,2,0,2,마포구,서교동
1,ST-5,103. 망원역 2번출구 앞,126.910835,37.554951,14,0,4,2,6,마포구,망원1동
2,ST-6,104. 합정역 1번출구 앞,126.915085,37.550739,13,0,6,0,6,마포구,서교동
3,ST-7,105. 합정역 5번출구 앞,126.914825,37.550007,5,0,0,0,0,마포구,서교동
4,ST-8,106. 합정역 7번출구 앞,126.912827,37.548645,12,0,3,0,3,마포구,합정동
...,...,...,...,...,...,...,...,...,...,...,...
2730,ST-3418,6185.가양나들목,126.843452,37.573410,8,0,5,2,7,강서구,가양1동
2731,ST-3415,6187.마곡119안전센터 맞은편,126.820724,37.555347,12,0,2,4,6,강서구,공항동
2732,ST-3419,6188.금호아파트,126.864754,37.556110,17,0,38,7,45,강서구,염창동
2733,ST-3424,6189.데시앙플렉스 지식산업센터,126.848305,37.564484,11,0,2,0,2,강서구,가양1동
2734,ST-3421,6190.마곡광장(마곡나루역 6번출구),126.827385,37.566147,10,0,12,0,12,강서구,가양1동

추가된 파생 변수에 발생된 문제점을 처리한다.

In [66]:
bike.info()

<class 'pandas.DataFrame'>
RangeIndex: 2735 entries, 0 to 2734
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stationId           2735 non-null   str
 1   stationName         2735 non-null   str
 2   stationLongitude    2735 non-null   float64
 3   stationLatitude     2735 non-null   float64
 4   rackTotCnt          2735 non-null   int64
 5   parkingBikeTotCnt   2735 non-null   int64
 6   parkingQRBikeCnt    2735 non-null   int64
 7   parkingELECBikeCnt  2735 non-null   int64
 8   parking             2735 non-null   int64
 9   goo                 2735 non-null   str
 10  dong                2735 non-null   str
dtypes: float64(2), int64(5), str(4)
memory usage: 235.2 KB

In [67]:
bike[bike.goo.isnull() | bike.dong.isnull()]

Empty DataFrame
Columns: [stationId, stationName, stationLongitude, stationLatitude, rackTotCnt, parkingBikeTotCnt, parkingQRBikeCnt, parkingELECBikeCnt, parking, goo, dong]
Index: []

In [68]:
bike[bike.goo.isnull() | bike.dong.isnull()].stationId

Series([], Name: stationId, dtype: str)

In [69]:
errorList = list(bike[bike.goo.isnull() | bike.dong.isnull()].stationId)
print(type(errorList))
print(errorList)

<class 'list'>
[]

역지오코딩 실행 후 'goo'와 'dong'이라는 파생 변수에 NaN이 있을 경우 실행하는 코드

In [70]:
for error in errorList:
    bike_error = bike[bike.stationId == error]
    # print(bike_error)
    lat_lot = f"{bike_error.iloc[0, 5]},{bike_error.iloc[0, 4]}"
    # print(lat_lot)
    address = geocoding_reverse(lat_lon)
    address = str(address).split(', ')
    bike.loc[i, 'goo'] = address[-3]
    bike.loc[i, 'dong'] = address[-4]
    
bike[bike.goo.isnull() | bike.dong.isnull()]

Empty DataFrame
Columns: [stationId, stationName, stationLongitude, stationLatitude, rackTotCnt, parkingBikeTotCnt, parkingQRBikeCnt, parkingELECBikeCnt, parking, goo, dong]
Index: []

In [166]:
bike.goo.value_counts()

goo
송파구     218
강서구     194
영등포구    172
강남구     172
노원구     148
서초구     143
마포구     120
강동구     117
구로구     115
양천구     106
종로구      97
은평구      96
중랑구      95
중구       91
동대문구     91
광진구      89
성동구      89
용산구      88
서대문구     81
성북구      80
도봉구      72
금천구      71
동작구      67
관악구      66
강북구      57
Name: count, dtype: int64

In [167]:
bike[(bike.goo == '서울특별시') | (bike.goo == '의정부시') | (bike.goo == '하남시')]

Empty DataFrame
Columns: [stationId, stationName, stationLongitude, stationLatitude, rackTotCnt, parkingBikeTotCnt, parkingQRBikeCnt, parkingELECBikeCnt, parking, goo, dong]
Index: []

In [164]:
address = geocoding_reverse('37.484833,127.149918')
address = str(address).split(', ')
print(address)

['북위례2', '657-12', '위례대로', '학암동', '위례동', '송파구', '서울특별시', '경기도', '13011', '대한민국']

In [165]:
bike.loc[2655, 'goo'] = '송파구'
bike.loc[2655, 'dong'] = '위례동'

In [168]:
bike.to_csv('./data/bike_20260709_ok.csv', index=False)
bike = pd.read_csv('./data/bike_20260709_ok.csv')
bike

,stationId,stationName,stationLongitude,stationLatitude,rackTotCnt,parkingBikeTotCnt,parkingQRBikeCnt,parkingELECBikeCnt,parking,goo,dong
0,ST-4,102. 망원역 1번출구 앞,126.910629,37.555649,15,0,2,0,2,마포구,서교동
1,ST-5,103. 망원역 2번출구 앞,126.910835,37.554951,14,0,4,2,6,마포구,망원1동
2,ST-6,104. 합정역 1번출구 앞,126.915085,37.550739,13,0,6,0,6,마포구,서교동
3,ST-7,105. 합정역 5번출구 앞,126.914825,37.550007,5,0,0,0,0,마포구,서교동
4,ST-8,106. 합정역 7번출구 앞,126.912827,37.548645,12,0,3,0,3,마포구,합정동
...,...,...,...,...,...,...,...,...,...,...,...
2730,ST-3418,6185.가양나들목,126.843452,37.573410,8,0,5,2,7,강서구,가양1동
2731,ST-3415,6187.마곡119안전센터 맞은편,126.820724,37.555347,12,0,2,4,6,강서구,공항동
2732,ST-3419,6188.금호아파트,126.864754,37.556110,17,0,38,7,45,강서구,염창동
2733,ST-3424,6189.데시앙플렉스 지식산업센터,126.848305,37.564484,11,0,2,0,2,강서구,가양1동
2734,ST-3421,6190.마곡광장(마곡나루역 6번출구),126.827385,37.566147,10,0,12,0,12,강서구,가양1동

In [169]:
bike[bike.goo.isnull() | bike.dong.isnull()]

Empty DataFrame
Columns: [stationId, stationName, stationLongitude, stationLatitude, rackTotCnt, parkingBikeTotCnt, parkingQRBikeCnt, parkingELECBikeCnt, parking, goo, dong]
Index: []

종로구 따릉이 스테이션 위치 시각화

In [170]:
bike.goo.value_counts()

goo
송파구     218
강서구     194
영등포구    172
강남구     172
노원구     148
서초구     143
마포구     120
강동구     117
구로구     115
양천구     106
종로구      97
은평구      96
중랑구      95
중구       91
동대문구     91
광진구      89
성동구      89
용산구      88
서대문구     81
성북구      80
도봉구      72
금천구      71
동작구      67
관악구      66
강북구      57
Name: count, dtype: int64

In [171]:
data = bike[bike.goo == '종로구']

In [173]:
bike_map = folium.Map(location=[data.stationLatitude.mean(), data.stationLongitude.mean()], zoom_start=14)

for i in data.index:
    try:
        stationName = data.loc[i, 'stationName'].split('.')[1].strip()
    except:
        stationName = data.loc[i, 'stationName'].split('.')[0].strip()
    string = '스테이션 이름: {}<br>현재 주차된 자전거 대수: {}대'.format(
        stationName,
        data.loc[i, 'parking']
    )
    popup = folium.Popup(string, max_width=300)
    folium.Marker(
        location=[data.loc[i, 'stationLatitude'], data.loc[i, 'stationLongitude']], 
        popup=popup,
    ).add_to(bike_map)

bike_map.save('./output/bike_map.html')
bike_map

마포구 서교동 따릉이 스테이션 위치 시각화

In [174]:
data = bike[(bike.goo == '마포구') & (bike.dong == '서교동')]
data

,stationId,stationName,stationLongitude,stationLatitude,rackTotCnt,parkingBikeTotCnt,parkingQRBikeCnt,parkingELECBikeCnt,parking,goo,dong
0,ST-4,102. 망원역 1번출구 앞,126.910629,37.555649,15,0,2,0,2,마포구,서교동
2,ST-6,104. 합정역 1번출구 앞,126.915085,37.550739,13,0,6,0,6,마포구,서교동
3,ST-7,105. 합정역 5번출구 앞,126.914825,37.550007,5,0,0,0,0,마포구,서교동
5,ST-9,107. 수협 연남동지점,126.918716,37.557846,10,0,7,0,7,마포구,서교동
6,ST-10,108. 서교동 사거리,126.918617,37.552746,12,0,0,0,0,마포구,서교동
8,ST-18,113. 홍대입구역 2번출구 앞,126.923821,37.557438,28,0,32,0,32,마포구,서교동
9,ST-20,114. 홍대입구역 8번출구 앞,126.924423,37.557060,15,0,5,0,5,마포구,서교동
308,ST-2152,493.홍대입구역 6번출구,126.928856,37.556576,7,0,9,0,9,마포구,서교동
1711,ST-2167,3009. 홍대입구역 사거리,126.920235,37.554501,20,0,5,0,5,마포구,서교동
1712,ST-2168,3010.홍대입구역 3번출구,126.925385,37.558296,15,0,16,1,17,마포구,서교동
2144,ST-2531,4207. 아만티호텔 앞,126.918854,37.557308,10,0,2,0,2,마포구,서교동
2145,ST-2532,4208. 스타벅스(동교동) 앞,126.919868,37.556660,10,0,4,0,4,마포구,서교동

In [175]:
bike_map = folium.Map(location=[data.stationLatitude.mean(), data.stationLongitude.mean()], zoom_start=15)

for i in data.index:
    string = ' {}<br>일반따릉이: {}<br>새싹따릉이: {}'.format(
        data.loc[i, 'stationName'],
        data.loc[i, 'parkingQRBikeCnt'],
        data.loc[i, 'parkingELECBikeCnt']
    )
    popup = folium.Popup(string, max_width=300)
    folium.Marker(
        location=[data.loc[i, 'stationLatitude'], data.loc[i, 'stationLongitude']], 
        popup=popup,
    ).add_to(bike_map)

bike_map.save('./output/bike_map.html')
bike_map

따릉이 스테이션 이름에 '마포'가 포함된 따릉이 스테이션 위치 시각화

In [176]:
data = bike[bike.stationName.str.find('마포') >= 0]
data

,stationId,stationName,stationLongitude,stationLatitude,rackTotCnt,parkingBikeTotCnt,parkingQRBikeCnt,parkingELECBikeCnt,parking,goo,dong
15,ST-23,121. 마포소방서 앞,126.933174,37.549767,15,0,8,4,12,마포구,신수동
35,ST-204,146. 마포역 2번출구 뒤,126.945824,37.539936,12,0,10,0,10,마포구,용강동
36,ST-205,147. 마포역 4번출구 뒤,126.945915,37.539272,5,0,3,7,10,마포구,도화동
40,ST-211,154. 마포구청역,126.905495,37.560909,11,0,16,0,16,마포구,성산1동
67,ST-343,185. 마포 신수공원 앞,126.934296,37.542545,15,0,1,0,1,마포구,신수동
238,ST-83,407. 마포구 육아종합지원센터,126.883675,37.580631,17,0,9,4,13,마포구,상암동
250,ST-87,419. 홈플러스 마포점 앞,126.899429,37.568420,21,0,14,13,27,마포구,성산2동
252,ST-82,421. 마포구청 앞,126.901863,37.565746,8,0,0,1,1,마포구,성산2동
262,ST-1494,432. 마포중앙도서관,126.908203,37.563339,10,0,0,0,0,마포구,성산1동
1707,ST-2163,3005.마포구청 청사내,126.902184,37.566246,10,0,3,0,3,마포구,성산2동
2149,ST-2536,4213. 마포구중앙도서관 정문 앞,126.908150,37.564156,15,0,17,0,17,마포구,성산1동
2158,ST-2978,4226. 마포프레스티지자이 1,126.946693,37.551529,14,0,10,1,11,마포구,염리동
2631,ST-3130,5503. 마포아트센터 앞,126.945801,37.550343,5,0,11,7,18,마포구,대흥동
2637,ST-3355,5513. 마포음식문화거리,126.942665,37.540737,13,0,16,4,20,마포구,용강동

In [177]:
bike_map = folium.Map(location=[data.stationLatitude.mean(), data.stationLongitude.mean()], zoom_start=14)

for i in data.index:
    string = ' {}<br>일반따릉이: {}<br>새싹따릉이: {}'.format(
        data.loc[i, 'stationName'],
        data.loc[i, 'parkingQRBikeCnt'],
        data.loc[i, 'parkingELECBikeCnt']
    )
    popup = folium.Popup(string, max_width=300)
    folium.Marker(
        location=[data.loc[i, 'stationLatitude'], data.loc[i, 'stationLongitude']], 
        popup=popup,
    ).add_to(bike_map)

bike_map.save('./output/bike_map.html')
bike_map