In [1]:
import warnings
warnings.filterwarnings(action='ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

분석하기 좋은 데이터

분석하기 좋은 데이터는 데이터 집합을 분석하기 좋은 형태로 만들어 놓은 것을 말하고 데이터 분석 작업에서 데이터 정리는 아주 중요한 작업으로 실제 데이터 분석작업의 70% 이상을 차지하고 있는 작업이 데이터 정리(전처리) 작업이다.  
분석하기 좋은 데이터는 데이터를 분석 목적에 맞는 데이터를 모아서(수집) 새로운 표(table, 데이터프레임)를 만들어야 하고 측정한 값(데이터 1건)은 행으로 변수(특성, 속성)들을 열로 고성하며 이 모든 조건을 만족하는 데이터를 깔끔한 데이터(good data)라고 부른다.

In [2]:
df1 = pd.read_csv('./data/concat_1.csv')
df1

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [3]:
df2 = pd.read_csv('./data/concat_2.csv')
df2

    A   B   C   D
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7

In [4]:
df3 = pd.read_csv('./data/concat_3.csv')
df3

     A    B    C    D
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

concat() 메소드는 데이터프레임을 연결한다.  
연결하려는 데이터프레임을 리스트에 담아서 concat() 메소드에 전달하면 연결한 데이터프레임을 리턴한다.  
concat([데이터프레임1, 데이터프레임2, ...][, axis])  
axis 속성을 생략하면 0이 기본값이고 위에서 아래 방향으로 연결하고 axis=1로 지정하면 왼쪽에서 오른쪽 방향으로 연결한다.

In [5]:
row_concat = pd.concat([df1, df2, df3]) # pd.concat([df1, df2, df3], axis=0), 아래로 붙인다.
row_concat

     A    B    C    D
0   a0   b0   c0   d0
1   a1   b1   c1   d1
2   a2   b2   c2   d2
3   a3   b3   c3   d3
0   a4   b4   c4   d4
1   a5   b5   c5   d5
2   a6   b6   c6   d6
3   a7   b7   c7   d7
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [6]:
col_concat = pd.concat([df1, df2, df3], axis=1) # 옆으로 붙인다.
col_concat

    A   B   C   D   A   B   C   D    A    B    C    D
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

데이터프레임에 데이터 1건을 추가하기

In [7]:
row_series = pd.Series(['n1', 'n2', 'n3', 'n4']) # 시리즈
row_series

0    n1
1    n2
2    n3
3    n4
dtype: str

In [8]:
# axis를 생략해서 axis=0인 상태에서 시리즈가 새로운 행으로 추가되지 않고 새로운 열로 추가된다.
# 시리즈에 열 이름이 없기때문에 시리즈를 데이터프레임에 새로운 행으로 추가하려 할 때 제대로 추가되지 않는다.
# 추가하는 시리즈를 새로운 열로 간주해서 0이라는 열이 추가된다.
pd.concat([df1, row_series])

     A    B    C    D    0
0   a0   b0   c0   d0  NaN
1   a1   b1   c1   d1  NaN
2   a2   b2   c2   d2  NaN
3   a3   b3   c3   d3  NaN
0  NaN  NaN  NaN  NaN   n1
1  NaN  NaN  NaN  NaN   n2
2  NaN  NaN  NaN  NaN   n3
3  NaN  NaN  NaN  NaN   n4

In [9]:
row_df = pd.DataFrame(['n1', 'n2', 'n3', 'n4']) # 열 방향 데이터프레임
row_df

    0
0  n1
1  n2
2  n3
3  n4

In [10]:
pd.concat([df1, row_df])

     A    B    C    D    0
0   a0   b0   c0   d0  NaN
1   a1   b1   c1   d1  NaN
2   a2   b2   c2   d2  NaN
3   a3   b3   c3   d3  NaN
0  NaN  NaN  NaN  NaN   n1
1  NaN  NaN  NaN  NaN   n2
2  NaN  NaN  NaN  NaN   n3
3  NaN  NaN  NaN  NaN   n4

DataFrame()의 인수로 ['n1', 'n2', 'n3', 'n4']와 같이 1차원 리스트를 전달하면 데이터 하나하나를 개별 데이터로 취급해서 열방향 데이터프레임이 생성된다.  
[['n1', 'n2', 'n3', 'n4']]와 같이 2차원 리스트로 전달하면 1차원 리스트 전체를 1개의 데이터로 취급해서 행 방향 데이터프레임이 생성된다.

In [11]:
row_df = pd.DataFrame([['n1', 'n2', 'n3', 'n4']]) # 행 방향 데이터프레임
row_df

    0   1   2   3
0  n1  n2  n3  n4

In [12]:
pd.concat([df1, row_df])

     A    B    C    D    0    1    2    3
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN   n1   n2   n3   n4

DataFrame()으로 데이터프레임을 생성할 때 열 인덱스를 지정하지 않으면 pandas가 자동으로 0, 1, 2, 3, ...와 같은 방식으로 열 인덱스를 지정하기 때문에 columns 속성으로 열 인덱스를 전달한다.

In [13]:
# row_df = pd.DataFrame([['n1', 'n2', 'n3', 'n4']], columns=['A', 'B', 'C', 'D'])
row_df = pd.DataFrame([['n1', 'n2', 'n3', 'n4']], columns=df1.columns)
row_df

    A   B   C   D
0  n1  n2  n3  n4

In [14]:
pd.concat([df1, row_df])

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
0  n1  n2  n3  n4

concat() 메소드로 데이터프레임을 연결하면 발생되는 중복되는 인덱스를 무시하고 인덱스를 다시 부여하려면 ignore_index 속성의 속성값을 True로 지정하면 인덱스가 0부터 1씩 증가하는 값으로 다시 부여된다.

In [15]:
row_concat = pd.concat([df1, df2, df3], ignore_index=True)
row_concat

      A    B    C    D
0    a0   b0   c0   d0
1    a1   b1   c1   d1
2    a2   b2   c2   d2
3    a3   b3   c3   d3
4    a4   b4   c4   d4
5    a5   b5   c5   d5
6    a6   b6   c6   d6
7    a7   b7   c7   d7
8    a8   b8   c8   d8
9    a9   b9   c9   d9
10  a10  b10  c10  d10
11  a11  b11  c11  d11

In [16]:
col_concat = pd.concat([df1, df2, df3], axis=1, ignore_index=True)
col_concat

   0   1   2   3   4   5   6   7    8    9    10   11
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

In [17]:
print(df1.columns)
df2.columns = ['E', 'F', 'G', 'H']
print(df2.columns)
df3.columns = ['A', 'C', 'F', 'H']
print(df3.columns)

Index(['A', 'B', 'C', 'D'], dtype='str')
Index(['E', 'F', 'G', 'H'], dtype='str')
Index(['A', 'C', 'F', 'H'], dtype='str')

위와 같이 데이터프레임의 열 인덱스를 다시 부여하고 concat() 메소드로 연결하면 데이터프레임에 없는 열 인덱스의 데이터는 NaN(누락값, 결측치)으로 처리된다.

In [18]:
pd.concat([df1, df2, df3], ignore_index=True)

      A    B    C    D    E    F    G    H
0    a0   b0   c0   d0  NaN  NaN  NaN  NaN
1    a1   b1   c1   d1  NaN  NaN  NaN  NaN
2    a2   b2   c2   d2  NaN  NaN  NaN  NaN
3    a3   b3   c3   d3  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   a4   b4   c4   d4
5   NaN  NaN  NaN  NaN   a5   b5   c5   d5
6   NaN  NaN  NaN  NaN   a6   b6   c6   d6
7   NaN  NaN  NaN  NaN   a7   b7   c7   d7
8    a8  NaN   b8  NaN  NaN   c8  NaN   d8
9    a9  NaN   b9  NaN  NaN   c9  NaN   d9
10  a10  NaN  b10  NaN  NaN  c10  NaN  d10
11  a11  NaN  b11  NaN  NaN  c11  NaN  d11

concat() 메소드의 join 속성의 기본값은 'outer'이고 공통으로 데이터가 들어있는(NaN이 없는) 열에 신경쓰지 않고 연결한다. => NaN이 대량 발생된다.

In [19]:
pd.concat([df1, df2, df3], ignore_index=True, join='outer')

      A    B    C    D    E    F    G    H
0    a0   b0   c0   d0  NaN  NaN  NaN  NaN
1    a1   b1   c1   d1  NaN  NaN  NaN  NaN
2    a2   b2   c2   d2  NaN  NaN  NaN  NaN
3    a3   b3   c3   d3  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   a4   b4   c4   d4
5   NaN  NaN  NaN  NaN   a5   b5   c5   d5
6   NaN  NaN  NaN  NaN   a6   b6   c6   d6
7   NaN  NaN  NaN  NaN   a7   b7   c7   d7
8    a8  NaN   b8  NaN  NaN   c8  NaN   d8
9    a9  NaN   b9  NaN  NaN   c9  NaN   d9
10  a10  NaN  b10  NaN  NaN  c10  NaN  d10
11  a11  NaN  b11  NaN  NaN  c11  NaN  d11

concat() 메소드의 join 속성값을 'inner'로 지정하면 공통으로 데이터가 들어있는(NaN이 없는) 열만 연결한다.

In [20]:
pd.concat([df1, df2, df3], ignore_index=True, join='inner')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [21]:
pd.concat([df1, df3], ignore_index=True, join='inner')

     A    C
0   a0   c0
1   a1   c1
2   a2   c2
3   a3   c3
4   a8   b8
5   a9   b9
6  a10  b10
7  a11  b11

In [22]:
pd.concat([df2, df3], ignore_index=True, join='inner')

     F    H
0   b4   d4
1   b5   d5
2   b6   d6
3   b7   d7
4   c8   d8
5   c9   d9
6  c10  d10
7  c11  d11

In [23]:
print(df1.index)
df2.index = [4, 5, 6, 7]
print(df2.index)
df3.index = [0, 2, 5, 7]
print(df3.index)

RangeIndex(start=0, stop=4, step=1)
Index([4, 5, 6, 7], dtype='int64')
Index([0, 2, 5, 7], dtype='int64')

In [24]:
pd.concat([df1, df2, df3], axis=1, ignore_index=True, join='outer')

    0    1    2    3    4    5    6    7    8    9    10   11
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN   a8   b8   c8   d8
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN   a9   b9   c9   d9
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   a4   b4   c4   d4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   a5   b5   c5   d5  a10  b10  c10  d10
6  NaN  NaN  NaN  NaN   a6   b6   c6   d6  NaN  NaN  NaN  NaN
7  NaN  NaN  NaN  NaN   a7   b7   c7   d7  a11  b11  c11  d11

In [25]:
pd.concat([df1, df2, df3], axis=1, ignore_index=True, join='inner')

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
Index: []

In [26]:
pd.concat([df1, df3], axis=1, ignore_index=True, join='inner')

    0   1   2   3   4   5   6   7
0  a0  b0  c0  d0  a8  b8  c8  d8
2  a2  b2  c2  d2  a9  b9  c9  d9

In [27]:
pd.concat([df2, df3], axis=1, ignore_index=True, join='inner')

    0   1   2   3    4    5    6    7
5  a5  b5  c5  d5  a10  b10  c10  d10
7  a7  b7  c7  d7  a11  b11  c11  d11

merge() 메소드는 2개의 데이터프레임을 병합한다.  
기본값으로 내부 조인을 실행하며 merge() 메소드를 실행한 데이터프레임이 left로 지정되고 merge() 메소드의 인수로 지정한 데이터프레임이 right로 지정된다.  
left_on 속성과 right_on 속성은 각각 왼쪽과 오른쪽의 데이터프레임에서 일치해야 할 열 이름을 지정하고 how 속성으로 두 데이터프레임의 병합 방법을 지정한다.  
왼쪽데이터프레임.merge(오른쪽데이터프레임, left_on, right_on[, how])

survey_person.csv => 조사한 사람  
survey_site.csv => 조사 위치  
survey_survey.csv => 기상 정보  
survey_visited.csv => 조사한 날짜

In [28]:
person = pd.read_csv('./data/survey_person.csv')
person

      ident   personal    family
0      dyer    William      Dyer
1        pb      Frank   Pabodie
2      lake   Anderson      Lake
3       roe  Valentina   Roerich
4  danforth      Frank  Danforth

In [29]:
site = pd.read_csv('./data/survey_site.csv')
site

    name    lat    long
0   DR-1 -49.85 -128.57
1   DR-3 -47.15 -126.72
2  MSK-4 -48.87 -123.40

In [30]:
survey = pd.read_csv('./data/survey_survey.csv')
survey

    taken person quant  reading
0     619   dyer   rad     9.82
1     619   dyer   sal     0.13
2     622   dyer   rad     7.80
3     622   dyer   sal     0.09
4     734     pb   rad     8.41
5     734   lake   sal     0.05
6     734     pb  temp   -21.50
7     735     pb   rad     7.22
8     735    NaN   sal     0.06
9     735    NaN  temp   -26.00
10    751     pb   rad     4.35
11    751     pb  temp   -18.50
12    751   lake   sal     0.10
13    752   lake   rad     2.19
14    752   lake   sal     0.09
15    752   lake  temp   -16.00
16    752    roe   sal    41.60
17    837   lake   rad     1.46
18    837   lake   sal     0.21
19    837    roe   sal    22.50
20    844    roe   rad    11.25

In [31]:
visited = pd.read_csv('./data/survey_visited.csv')
visited

   ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734   DR-3  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3         NaN
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

site 데이터프레임과 visited 데이터프레임의 merge

In [32]:
print(site.columns)
print(visited.columns)

Index(['name', 'lat', 'long'], dtype='str')
Index(['ident', 'site', 'dated'], dtype='str')

how 속성을 두 데이터프레임을 병합하는 방법을 지정한다. 기본값은 how='inner' 이다.  
how 속성을 생략하거나 'inner'(내부 조인)로 지정하면 두 데이터프레임에 공통적으로 포함된 값이 존재하는 데이터만 병합된다.

In [33]:
# site.merge(visited, left_on='name', right_on='site')
site.merge(visited, left_on='name', right_on='site', how='inner')

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-1 -49.85 -128.57    622   DR-1  1927-02-10
2   DR-1 -49.85 -128.57    844   DR-1  1932-03-22
3   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
4   DR-3 -47.15 -126.72    735   DR-3  1930-01-12
5   DR-3 -47.15 -126.72    751   DR-3  1930-02-26
6   DR-3 -47.15 -126.72    752   DR-3         NaN
7  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

In [34]:
site.merge(visited, left_on='name', right_on='site', how='outer')

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-1 -49.85 -128.57    622   DR-1  1927-02-10
2   DR-1 -49.85 -128.57    844   DR-1  1932-03-22
3   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
4   DR-3 -47.15 -126.72    735   DR-3  1930-01-12
5   DR-3 -47.15 -126.72    751   DR-3  1930-02-26
6   DR-3 -47.15 -126.72    752   DR-3         NaN
7  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

In [35]:
site.merge(visited, left_on='name', right_on='site', how='left')

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-1 -49.85 -128.57    622   DR-1  1927-02-10
2   DR-1 -49.85 -128.57    844   DR-1  1932-03-22
3   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
4   DR-3 -47.15 -126.72    735   DR-3  1930-01-12
5   DR-3 -47.15 -126.72    751   DR-3  1930-02-26
6   DR-3 -47.15 -126.72    752   DR-3         NaN
7  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

In [36]:
site.merge(visited, left_on='name', right_on='site', how='right')

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-1 -49.85 -128.57    622   DR-1  1927-02-10
2   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
3   DR-3 -47.15 -126.72    735   DR-3  1930-01-12
4   DR-3 -47.15 -126.72    751   DR-3  1930-02-26
5   DR-3 -47.15 -126.72    752   DR-3         NaN
6  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14
7   DR-1 -49.85 -128.57    844   DR-1  1932-03-22

person 데이터프레임과 survey 데이터프레임의 merge

In [37]:
print(person.columns)
print(survey.columns)

Index(['ident', 'personal', 'family'], dtype='str')
Index(['taken', 'person', 'quant', 'reading'], dtype='str')

In [38]:
p2s = person.merge(survey, left_on='ident', right_on='person', how='inner')
p2s

   ident   personal   family  taken person quant  reading
0   dyer    William     Dyer    619   dyer   rad     9.82
1   dyer    William     Dyer    619   dyer   sal     0.13
2   dyer    William     Dyer    622   dyer   rad     7.80
3   dyer    William     Dyer    622   dyer   sal     0.09
4     pb      Frank  Pabodie    734     pb   rad     8.41
5     pb      Frank  Pabodie    734     pb  temp   -21.50
6     pb      Frank  Pabodie    735     pb   rad     7.22
7     pb      Frank  Pabodie    751     pb   rad     4.35
8     pb      Frank  Pabodie    751     pb  temp   -18.50
9   lake   Anderson     Lake    734   lake   sal     0.05
10  lake   Anderson     Lake    751   lake   sal     0.10
11  lake   Anderson     Lake    752   lake   rad     2.19
12  lake   Anderson     Lake    752   lake   sal     0.09
13  lake   Anderson     Lake    752   lake  temp   -16.00
14  lake   Anderson     Lake    837   lake   rad     1.46
15  lake   Anderson     Lake    837   lake   sal     0.21
16   roe  Valentina  Roerich    752    roe   sal    41.60
17   roe  Valentina  Roerich    837    roe   sal    22.50
18   roe  Valentina  Roerich    844    roe   rad    11.25

how 속성을 'outer'(외부 조인)로 지정하면 두 데이터프레임의 모든 데이터가 병합된다.

In [39]:
p2s = person.merge(survey, left_on='ident', right_on='person', how='outer')
p2s

       ident   personal    family  taken person quant  reading
0   danforth      Frank  Danforth    NaN    NaN   NaN      NaN
1       dyer    William      Dyer  619.0   dyer   rad     9.82
2       dyer    William      Dyer  619.0   dyer   sal     0.13
3       dyer    William      Dyer  622.0   dyer   rad     7.80
4       dyer    William      Dyer  622.0   dyer   sal     0.09
5       lake   Anderson      Lake  734.0   lake   sal     0.05
6       lake   Anderson      Lake  751.0   lake   sal     0.10
7       lake   Anderson      Lake  752.0   lake   rad     2.19
8       lake   Anderson      Lake  752.0   lake   sal     0.09
9       lake   Anderson      Lake  752.0   lake  temp   -16.00
10      lake   Anderson      Lake  837.0   lake   rad     1.46
11      lake   Anderson      Lake  837.0   lake   sal     0.21
12        pb      Frank   Pabodie  734.0     pb   rad     8.41
13        pb      Frank   Pabodie  734.0     pb  temp   -21.50
14        pb      Frank   Pabodie  735.0     pb   rad     7.22
15        pb      Frank   Pabodie  751.0     pb   rad     4.35
16        pb      Frank   Pabodie  751.0     pb  temp   -18.50
17       roe  Valentina   Roerich  752.0    roe   sal    41.60
18       roe  Valentina   Roerich  837.0    roe   sal    22.50
19       roe  Valentina   Roerich  844.0    roe   rad    11.25
20       NaN        NaN       NaN  735.0    NaN   sal     0.06
21       NaN        NaN       NaN  735.0    NaN  temp   -26.00

how 속성을 how='left'(왼쪽 외부 조인)로 지정하면 왼쪽 데이터프레임의 모든 데이터와 오른쪽 데이터프레임에 있는 공통적으로 포함된 데이터가 병합된다.

In [40]:
p2s = person.merge(survey, left_on='ident', right_on='person', how='left')
p2s

       ident   personal    family  taken person quant  reading
0       dyer    William      Dyer  619.0   dyer   rad     9.82
1       dyer    William      Dyer  619.0   dyer   sal     0.13
2       dyer    William      Dyer  622.0   dyer   rad     7.80
3       dyer    William      Dyer  622.0   dyer   sal     0.09
4         pb      Frank   Pabodie  734.0     pb   rad     8.41
5         pb      Frank   Pabodie  734.0     pb  temp   -21.50
6         pb      Frank   Pabodie  735.0     pb   rad     7.22
7         pb      Frank   Pabodie  751.0     pb   rad     4.35
8         pb      Frank   Pabodie  751.0     pb  temp   -18.50
9       lake   Anderson      Lake  734.0   lake   sal     0.05
10      lake   Anderson      Lake  751.0   lake   sal     0.10
11      lake   Anderson      Lake  752.0   lake   rad     2.19
12      lake   Anderson      Lake  752.0   lake   sal     0.09
13      lake   Anderson      Lake  752.0   lake  temp   -16.00
14      lake   Anderson      Lake  837.0   lake   rad     1.46
15      lake   Anderson      Lake  837.0   lake   sal     0.21
16       roe  Valentina   Roerich  752.0    roe   sal    41.60
17       roe  Valentina   Roerich  837.0    roe   sal    22.50
18       roe  Valentina   Roerich  844.0    roe   rad    11.25
19  danforth      Frank  Danforth    NaN    NaN   NaN      NaN

how 속성을 how='right'(오른쪽 외부 조인)로 지정하면 오른쪽 데이터프레임의 모든 데이터와 왼쪽 데이터프레임에 있는 공통적으로 포함된 데이터가 병합된다.

In [41]:
p2s = person.merge(survey, left_on='ident', right_on='person', how='right')
p2s

   ident   personal   family  taken person quant  reading
0   dyer    William     Dyer    619   dyer   rad     9.82
1   dyer    William     Dyer    619   dyer   sal     0.13
2   dyer    William     Dyer    622   dyer   rad     7.80
3   dyer    William     Dyer    622   dyer   sal     0.09
4     pb      Frank  Pabodie    734     pb   rad     8.41
5   lake   Anderson     Lake    734   lake   sal     0.05
6     pb      Frank  Pabodie    734     pb  temp   -21.50
7     pb      Frank  Pabodie    735     pb   rad     7.22
8    NaN        NaN      NaN    735    NaN   sal     0.06
9    NaN        NaN      NaN    735    NaN  temp   -26.00
10    pb      Frank  Pabodie    751     pb   rad     4.35
11    pb      Frank  Pabodie    751     pb  temp   -18.50
12  lake   Anderson     Lake    751   lake   sal     0.10
13  lake   Anderson     Lake    752   lake   rad     2.19
14  lake   Anderson     Lake    752   lake   sal     0.09
15  lake   Anderson     Lake    752   lake  temp   -16.00
16   roe  Valentina  Roerich    752    roe   sal    41.60
17  lake   Anderson     Lake    837   lake   rad     1.46
18  lake   Anderson     Lake    837   lake   sal     0.21
19   roe  Valentina  Roerich    837    roe   sal    22.50
20   roe  Valentina  Roerich    844    roe   rad    11.25

visited 데이터프레임과 survey 데이터프레임의 merge

In [42]:
print(visited.columns)
print(survey.columns)

Index(['ident', 'site', 'dated'], dtype='str')
Index(['taken', 'person', 'quant', 'reading'], dtype='str')

In [43]:
v2s = visited.merge(survey, left_on='ident', right_on='taken', how='inner')
v2s

    ident   site       dated  taken person quant  reading
0     619   DR-1  1927-02-08    619   dyer   rad     9.82
1     619   DR-1  1927-02-08    619   dyer   sal     0.13
2     622   DR-1  1927-02-10    622   dyer   rad     7.80
3     622   DR-1  1927-02-10    622   dyer   sal     0.09
4     734   DR-3  1939-01-07    734     pb   rad     8.41
5     734   DR-3  1939-01-07    734   lake   sal     0.05
6     734   DR-3  1939-01-07    734     pb  temp   -21.50
7     735   DR-3  1930-01-12    735     pb   rad     7.22
8     735   DR-3  1930-01-12    735    NaN   sal     0.06
9     735   DR-3  1930-01-12    735    NaN  temp   -26.00
10    751   DR-3  1930-02-26    751     pb   rad     4.35
11    751   DR-3  1930-02-26    751     pb  temp   -18.50
12    751   DR-3  1930-02-26    751   lake   sal     0.10
13    752   DR-3         NaN    752   lake   rad     2.19
14    752   DR-3         NaN    752   lake   sal     0.09
15    752   DR-3         NaN    752   lake  temp   -16.00
16    752   DR-3         NaN    752    roe   sal    41.60
17    837  MSK-4  1932-01-14    837   lake   rad     1.46
18    837  MSK-4  1932-01-14    837   lake   sal     0.21
19    837  MSK-4  1932-01-14    837    roe   sal    22.50
20    844   DR-1  1932-03-22    844    roe   rad    11.25

p2s 데이터프레임과 v2s 데이터프레임의 merge

In [44]:
print(p2s.columns)
print(v2s.columns)

Index(['ident', 'personal', 'family', 'taken', 'person', 'quant', 'reading'], dtype='str')
Index(['ident', 'site', 'dated', 'taken', 'person', 'quant', 'reading'], dtype='str')

left_on 속성과 right_on 속성에 리스트로 묶어서 여러개의 열 인덱스를 전달할 수 있다.  
merge() 메소드를 실행하는 두 데이터프레임에 공통된 열 인덱스가 있으면 왼쪽 데이터프레임의 열 인덱스에는 '_x'라는 접미사가 자동으로 추가되고 오른쪽 데이터프레임의 열 인덱스에는 '_y'라는 접미사가 자동으로 추가된다.

In [45]:
p2s.merge(v2s, left_on=['ident', 'taken', 'quant', 'reading'], right_on=['person', 'taken', 'quant', 'reading'], how='inner')

,ident_x,personal,family,taken,person_x,quant,reading,ident_y,site,dated,person_y
0,dyer,William,Dyer,619,dyer,rad,9.82,619,DR-1,1927-02-08,dyer
1,dyer,William,Dyer,619,dyer,sal,0.13,619,DR-1,1927-02-08,dyer
2,dyer,William,Dyer,622,dyer,rad,7.80,622,DR-1,1927-02-10,dyer
3,dyer,William,Dyer,622,dyer,sal,0.09,622,DR-1,1927-02-10,dyer
4,pb,Frank,Pabodie,734,pb,rad,8.41,734,DR-3,1939-01-07,pb
5,lake,Anderson,Lake,734,lake,sal,0.05,734,DR-3,1939-01-07,lake
6,pb,Frank,Pabodie,734,pb,temp,-21.50,734,DR-3,1939-01-07,pb
7,pb,Frank,Pabodie,735,pb,rad,7.22,735,DR-3,1930-01-12,pb
8,NaN,NaN,NaN,735,NaN,sal,0.06,735,DR-3,1930-01-12,NaN
9,NaN,NaN,NaN,735,NaN,temp,-26.00,735,DR-3,1930-01-12,NaN
10,pb,Frank,Pabodie,751,pb,rad,4.35,751,DR-3,1930-02-26,pb
11,pb,Frank,Pabodie,751,pb,temp,-18.50,751,DR-3,1930-02-26,pb
12,lake,Anderson,Lake,751,lake,sal,0.10,751,DR-3,1930-02-26,lake
13,lake,Anderson,Lake,752,lake,rad,2.19,752,DR-3,NaN,lake
14,lake,Anderson,Lake,752,lake,sal,0.09,752,DR-3,NaN,lake
15,lake,Anderson,Lake,752,lake,temp,-16.00,752,DR-3,NaN,lake
16,roe,Valentina,Roerich,752,roe,sal,41.60,752,DR-3,NaN,roe
17,lake,Anderson,Lake,837,lake,rad,1.46,837,MSK-4,1932-01-14,lake
18,lake,Anderson,Lake,837,lake,sal,0.21,837,MSK-4,1932-01-14,lake
19,roe,Valentina,Roerich,837,roe,sal,22.50,837,MSK-4,1932-01-14,roe
20,roe,Valentina,Roerich,844,roe,rad,11.25,844,DR-1,1932-03-22,roe