In [1]:
import warnings
warnings.filterwarnings(action='ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

matplotlib을 확장한 시각화 라이브러리 seaborn을 사용하기 위해 설치하고 import 한다.

In [2]:
# !pip install seaborn
import seaborn as sns

load_dataset() 메소드를 사용해서 seaborn이 제공하는 데이터셋을 읽어 데이터프레임으로 얻어올 수 있다.

In [3]:
tips_df = sns.load_dataset('tips')
tips_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

자료형 변경하기

pandas의 category 자료형은 R의 factor와 같은 범주형 데이터를 의미한다. => 연산을 위한 데이터가 아니고 분류를 위한 데이터이다.

In [4]:
# total_bill 열의 데이터 타입은 pandas 2.x까지 object로 사용되었다.
print(tips_df.dtypes)

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

astype() 메소드를 사용해서 자료형을 변경할 수 있다.  
total_bill 열의 데이터를 float64 타입에서 str 타입으로 변환한다.

In [5]:
tips_df['total_bill'] = tips_df['total_bill'].astype(str)
tips_df

    total_bill   tip     sex smoker   day    time  size
0        16.99  1.01  Female     No   Sun  Dinner     2
1        10.34  1.66    Male     No   Sun  Dinner     3
2        21.01  3.50    Male     No   Sun  Dinner     3
3        23.68  3.31    Male     No   Sun  Dinner     2
4        24.59  3.61  Female     No   Sun  Dinner     4
..         ...   ...     ...    ...   ...     ...   ...
239      29.03  5.92    Male     No   Sat  Dinner     3
240      27.18  2.00  Female    Yes   Sat  Dinner     2
241      22.67  2.00    Male    Yes   Sat  Dinner     2
242      17.82  1.75    Male     No   Sat  Dinner     2
243      18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
print(tips_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    str
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(1), int64(1), str(1)
memory usage: 7.4 KB
None

잘못 입력한 문자열 처리하기

In [7]:
tips_df_miss = tips_df.head(10)
tips_df_miss

  total_bill   tip     sex smoker  day    time  size
0      16.99  1.01  Female     No  Sun  Dinner     2
1      10.34  1.66    Male     No  Sun  Dinner     3
2      21.01  3.50    Male     No  Sun  Dinner     3
3      23.68  3.31    Male     No  Sun  Dinner     2
4      24.59  3.61  Female     No  Sun  Dinner     4
5      25.29  4.71    Male     No  Sun  Dinner     4
6       8.77  2.00    Male     No  Sun  Dinner     2
7      26.88  3.12    Male     No  Sun  Dinner     4
8      15.04  1.96    Male     No  Sun  Dinner     2
9      14.78  3.23    Male     No  Sun  Dinner     2

In [8]:
tips_df_miss.loc[[1, 3, 5, 7], 'total_bill'] = 'missing'
# tips_df_miss.iloc[[1, 3, 5, 7], 0] = 'missing'
tips_df_miss

  total_bill   tip     sex smoker  day    time  size
0      16.99  1.01  Female     No  Sun  Dinner     2
1    missing  1.66    Male     No  Sun  Dinner     3
2      21.01  3.50    Male     No  Sun  Dinner     3
3    missing  3.31    Male     No  Sun  Dinner     2
4      24.59  3.61  Female     No  Sun  Dinner     4
5    missing  4.71    Male     No  Sun  Dinner     4
6       8.77  2.00    Male     No  Sun  Dinner     2
7    missing  3.12    Male     No  Sun  Dinner     4
8      15.04  1.96    Male     No  Sun  Dinner     2
9      14.78  3.23    Male     No  Sun  Dinner     2

In [9]:
# tips_df_miss 데이터프레임의 total_bill 열을 astype() 메소드를 사용해서 실수로 변환하려하면 'missing'이라는 문자열 때문에 에러가 발생된다.
tips_df_miss['total_bill'] = tips_df_miss['total_bill'].astype(float)

ValueError: could not convert string to float: 'missing'

In [10]:
# to_numeric() 메소드를 사용해도 'missing'이라는 문자열 때문에 에러가 발생된다.
# tips_df_miss['total_bill'] = pd.to_numeric(tips_df_miss['total_bill'])

# to_numeric() 메소드의 errors 속성을 사용하면 어느정도 오류 제어를 할 수 있다.
# errors 속성을 생략하면 'raise'가 기본값으로 사용되며 숫자로 변환할 수 없는 값이 있으면 에러를 발생시킨다.
tips_df_miss['total_bill'] = pd.to_numeric(tips_df_miss['total_bill'], errors='raise')

ValueError: Unable to parse string "missing" at position 1

In [11]:
# pandas 3.x 버전부터 errors 속성값으로 'ignore'를 지원하지 않는다. => 에러가 발생되면 명령을 무시한다. => 실행하지 않는다.
# errors 속성값으로 'coerce'를 지정하면 오류가 발생되는 데이터를 누락값으로 변경한다.
tips_df_miss['total_bill'] = pd.to_numeric(tips_df_miss['total_bill'], errors='coerce')
tips_df_miss

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1         NaN  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3         NaN  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5         NaN  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7         NaN  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

숫자로 변경할 수 없는 데이터를 누락값으로 변경한 후 07_pandas_4 파일의 누락값 처리하기를 이어 실행하면 된다.