In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib
import seaborn as sns
import sklearn
sklearn.set_config(display='text')

댓글을 군집화해 분석해 볼 것이다. 댓글 분석은 왜 필요할까? 분석해서 어디에 활용할 수 있을까? 다음과 같은 상황을 생각해 보자.

수백 수천 개 댓글을 다 읽어야 한다면?  
댓글 속에 제품에 대한 관심을 빈도수로 추출해야 한다면?  
쇼핑몰에서 제품 관련 이벤트를 진행할 때 고객이 어떤 제품을 선호하는지 알고 싶다면?  
고객 DB와 연계해 이벤트나 마케닝 세그먼트로 활용한다면?  
향후 마케팅 전략을 세울 때 활용한다면?

데이터는 IT 교육 사이트인 인프런의 새해 다짐 이벤트 댓글을 사용한다. 정답 레이블이 없는 데이터를 분류하고 시각화하는 방법에 초점을 맞출 것이다. 분석하려는 데이터는 정답 레이블이 없으므로 비지도 학습 군집화를 실습한다.

# 데이터 불러와서 전처리 하기

## 데이터 불러오기

In [2]:
df = pd.read_csv('./data/inflearn-event.csv')
df.shape

(2449, 1)

In [3]:
df.head()

                                                text
0  2020년 목표: 스프링 열심히 공부하서 직장에서 사랑받고 싶어요!!\r\n관심강의...
1  2020년 목표: C++ 열심히 공부해서, 학교에서 꼭 A 맞기..!! \r\n관심...
2                                2020년 목표 : 리액트 공부하기
3              40대 프로그래밍 시작! : 우리를 위한 프로그래밍 : 파이썬 중급
4                    2020년 목표 : 돌머리 비전공자가 멋진 전공자 되기!

In [4]:
df.tail()

                                                   text
2444  작년 한해도 일이 바쁘다, 야근해서 힘들다는 핑계로 ***님의 JPA 강의를 또 스...
2445  저는 졸업을 1년 남기고 있는 컴퓨터공학과 학생입니다. 졸업 프로젝트로 웹/앱 개발...
2446  에프터 이펙트를 써본 적은 있는데, 매번 기초만 배우다 말았어요. 이걸 할 줄 안다...
2447  저번에 인프런에서 페이스북 마케팅 강의를 듣고 많은 도움을 받았습니다. 마케팅 업무...
2448  인프런 0호 팀원이에요!\r\n그동안 서비스 개발 때문에 js 를 많이 했었는데 앞...

## 중복된 글 제거하기

온라인으로 수집한 데이터는 다양한 이유로 중복 생성 될 수 있다. 웹사이트에서 전송 버튼을 여러 번 누르거나, 새로 고침을 하거나, 네트워크나 UX 관련된 오류 문제가 발생되기도 한다. 중복 데이터가 있으면 빈도 분석이 제대로 되지 않기 때문에 중복 데이터를 제거한다.

중복되는 데이터가 있는지 확인한다.

In [5]:
print(len(df.text), len(set(df.text)))

2449 2410

판다스의 drop_duplicates() 메소드로 데이터의 중복을 제거할 수 있다.  
keep 속성의 기본값은 `first`이고 중복되는 데이터에 첫 번째 데이터를 제외하고 모두 제거하고 `last`는 마지막 데이터를 제외하고 모두 제거한다. 만약에 중복되는 데이터를 모두 제거하고 싶다면 `False`를 사용하면 된다.

In [6]:
print(df.shape)
df = df.drop_duplicates(['text'], keep='last')
print(df.shape)

(2449, 1)
(2410, 1)

## 소문자로 변환하기

전처리할 때는 원본을 따로 보존하는 것을 추천한다. 원본과 전처리 결과를 비교해 볼 수 있고 망쳤을 때 복원할 수 있기 때문이다.

In [7]:
df['origin_text'] = df.text
df.head()

,text,origin_text
0,2020년 목표: 스프링 열심히 공부하서 직장에서 사랑받고 싶어요!!\r\n관심강의...,2020년 목표: 스프링 열심히 공부하서 직장에서 사랑받고 싶어요!!\r\n관심강의...
1,"2020년 목표: C++ 열심히 공부해서, 학교에서 꼭 A 맞기..!! \r\n관심...","2020년 목표: C++ 열심히 공부해서, 학교에서 꼭 A 맞기..!! \r\n관심..."
3,40대 프로그래밍 시작! : 우리를 위한 프로그래밍 : 파이썬 중급,40대 프로그래밍 시작! : 우리를 위한 프로그래밍 : 파이썬 중급
4,2020년 목표 : 돌머리 비전공자가 멋진 전공자 되기!,2020년 목표 : 돌머리 비전공자가 멋진 전공자 되기!
5,2020 년목표: 비전공자(경영)가 전공자(it) 되기!!!,2020 년목표: 비전공자(경영)가 전공자(it) 되기!!!

파이썬은 같은 단어라도 대문자냐 소문자냐에 따라 다른 글자로 인식하므로 lower() 메소드로 모두 소문자로 변경한다.

In [8]:
df['text'] = df.text.str.lower()
df.head()

,text,origin_text
0,2020년 목표: 스프링 열심히 공부하서 직장에서 사랑받고 싶어요!!\r\n관심강의...,2020년 목표: 스프링 열심히 공부하서 직장에서 사랑받고 싶어요!!\r\n관심강의...
1,"2020년 목표: c++ 열심히 공부해서, 학교에서 꼭 a 맞기..!! \r\n관심...","2020년 목표: C++ 열심히 공부해서, 학교에서 꼭 A 맞기..!! \r\n관심..."
3,40대 프로그래밍 시작! : 우리를 위한 프로그래밍 : 파이썬 중급,40대 프로그래밍 시작! : 우리를 위한 프로그래밍 : 파이썬 중급
4,2020년 목표 : 돌머리 비전공자가 멋진 전공자 되기!,2020년 목표 : 돌머리 비전공자가 멋진 전공자 되기!
5,2020 년목표: 비전공자(경영)가 전공자(it) 되기!!!,2020 년목표: 비전공자(경영)가 전공자(it) 되기!!!

'파이썬', 'python'과 같이 의미는 같으나 표기가 다르게 되어 있는 단어도 하나로 통일하기 위해서 replace() 메소드로 치환한다.

In [9]:
df['text'] = df.text.str.replace('python', '파이썬').str.replace('react', '리액트').str.replace('pandas', '판다스').str.replace('javascript', '자바스크립트'
    ).str.replace('java', '자바').str.replace('mongodb', '몽고DB').str.replace('django', '장고')
df.head()

,text,origin_text
0,2020년 목표: 스프링 열심히 공부하서 직장에서 사랑받고 싶어요!!\r\n관심강의...,2020년 목표: 스프링 열심히 공부하서 직장에서 사랑받고 싶어요!!\r\n관심강의...
1,"2020년 목표: c++ 열심히 공부해서, 학교에서 꼭 a 맞기..!! \r\n관심...","2020년 목표: C++ 열심히 공부해서, 학교에서 꼭 A 맞기..!! \r\n관심..."
3,40대 프로그래밍 시작! : 우리를 위한 프로그래밍 : 파이썬 중급,40대 프로그래밍 시작! : 우리를 위한 프로그래밍 : 파이썬 중급
4,2020년 목표 : 돌머리 비전공자가 멋진 전공자 되기!,2020년 목표 : 돌머리 비전공자가 멋진 전공자 되기!
5,2020 년목표: 비전공자(경영)가 전공자(it) 되기!!!,2020 년목표: 비전공자(경영)가 전공자(it) 되기!!!

'관심강의'라는 텍스트가 있다. '관심 있는 강의', '관심있는 강의', '#관심강의' 등으로 다양하게 표현돼있어서 아래와 같이 replace() 메소드로 치환하려 했었으나 다양하게 표현된 텍스트가 너무 많아서 cav 파일 자체를 수정했다. ㅠㅠ

In [10]:
df['text'] = df.text.str.replace('관심 있는 강의', '관심강의').str.replace('관심있는 강의', '관심강의').str.replace('#관심강의', '관심강의')

'관심강의'를 기준으로 split() 메소드로 분할하면 학생이 관심있는 강의를 알 수 있다.

In [11]:
# df['course'] = df.text.apply(lambda x: x.split('관심강의')[-1])
df['course'] = df.text.str.split('관심강의').str[-1]
df['course'] = df.course.str.replace(':', '').str.strip()

In [12]:
df[['text', 'course']].head()

,text,course
0,2020년 목표: 스프링 열심히 공부하서 직장에서 사랑받고 싶어요!!\r\n관심강의...,스프링 웹 mvc
1,"2020년 목표: c++ 열심히 공부해서, 학교에서 꼭 a 맞기..!! \r\n관심...",***c++
3,40대 프로그래밍 시작! : 우리를 위한 프로그래밍 : 파이썬 중급,40대 프로그래밍 시작! 우리를 위한 프로그래밍 파이썬 중급
4,2020년 목표 : 돌머리 비전공자가 멋진 전공자 되기!,2020년 목표 돌머리 비전공자가 멋진 전공자 되기!
5,2020 년목표: 비전공자(경영)가 전공자(it) 되기!!!,2020 년목표 비전공자(경영)가 전공자(it) 되기!!!

search_keyword에 course 열에 저장된 관심강의에서 검색할 과목 이름을 저장하고 반복문을 실행해서 관심강의에 검색할 과목 이름을 contains() 메소드로 포함하고 있을 경우 검색어를 열 이름으로 하는 열에 True를 그렇치 않으면 False를 넣어준다.

In [13]:
search_keyword = ['파이썬', '크롤링', '넘파이', '판다스', '시각화', '데이터분석', '몽고DB', '머신러닝', '딥러닝', '자연어', 'llm', 'rag', 'langgraph', 'neo4j']
for keyword in search_keyword:
    df[keyword] = df.text.str.contains(keyword)

In [14]:
df.head()

,text,origin_text,course,파이썬,크롤링,넘파이,판다스,시각화,데이터분석,몽고DB,머신러닝,딥러닝,자연어,llm,rag,langgraph,neo4j
0,2020년 목표: 스프링 열심히 공부하서 직장에서 사랑받고 싶어요!!\r\n관심강의...,2020년 목표: 스프링 열심히 공부하서 직장에서 사랑받고 싶어요!!\r\n관심강의...,스프링 웹 mvc,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,"2020년 목표: c++ 열심히 공부해서, 학교에서 꼭 a 맞기..!! \r\n관심...","2020년 목표: C++ 열심히 공부해서, 학교에서 꼭 A 맞기..!! \r\n관심...",***c++,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,40대 프로그래밍 시작! : 우리를 위한 프로그래밍 : 파이썬 중급,40대 프로그래밍 시작! : 우리를 위한 프로그래밍 : 파이썬 중급,40대 프로그래밍 시작! 우리를 위한 프로그래밍 파이썬 중급,True,False,False,False,False,False,False,False,False,False,False,False,False,False
4,2020년 목표 : 돌머리 비전공자가 멋진 전공자 되기!,2020년 목표 : 돌머리 비전공자가 멋진 전공자 되기!,2020년 목표 돌머리 비전공자가 멋진 전공자 되기!,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,2020 년목표: 비전공자(경영)가 전공자(it) 되기!!!,2020 년목표: 비전공자(경영)가 전공자(it) 되기!!!,2020 년목표 비전공자(경영)가 전공자(it) 되기!!!,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [19]:
df[df.머신러닝 & df.딥러닝].head()

,text,origin_text,course,파이썬,크롤링,넘파이,판다스,시각화,데이터분석,몽고DB,머신러닝,딥러닝,자연어,llm,rag,langgraph,neo4j
45,sw 개발자입니다. 자기개발 및 업무 환경 개선을 위해 공부하고 싶습니다.\r\n관...,SW 개발자입니다. 자기개발 및 업무 환경 개선을 위해 공부하고 싶습니다.\r\n관...,"모두를 위한 딥러닝 - deep reinforcement learning, 그 외 ...",True,False,False,False,False,False,False,True,True,False,False,False,False,False
59,올해 졸업하기 전에 머신러닝을 마스터하고 싶습니다.\r\n관심강의: 모두를 위한 딥...,올해 졸업하기 전에 머신러닝을 마스터하고 싶습니다.\r\n관심강의: 모두를 위한 딥...,"모두를 위한 딥러닝 - deep reinforcement learning, 그 외 ...",True,False,False,False,False,False,False,True,True,False,False,False,False,False
236,금융인을 꿈꾸는 인문대생인데 인프런을 통해 그 꿈에 날개를 달 수 있으면 좋겠습니다...,금융인을 꿈꾸는 인문대생인데 인프런을 통해 그 꿈에 날개를 달 수 있으면 좋겠습니다...,금융인을 꿈꾸는 인문대생인데 인프런을 통해 그 꿈에 날개를 달 수 있으면 좋겠습니다...,False,False,False,False,False,False,False,True,True,False,False,False,False,False
262,인문게 졸업생인데 공학 계열로 진로를 변경하려 합니다. 인프런에서 '모두를 위한 딥...,인문게 졸업생인데 공학 계열로 진로를 변경하려 합니다. 인프런에서 '모두를 위한 딥...,r로 하는 웹 크롤링 - 입문편,False,True,False,False,False,False,False,True,True,False,False,False,False,False
279,올해 새롭게 딥러닝에 대한 공부를 시작하고자 합니다!\r\n관심강의 : 밑바닥부터 ...,올해 새롭게 딥러닝에 대한 공부를 시작하고자 합니다!\r\n관심강의 : 밑바닥부터 ...,"밑바닥부터 시작하는 머신러닝 입문, 공공 데이터 분석",False,False,False,False,False,False,False,True,True,False,False,False,False,False

이번에는 정규표현식을 사용해 '파이썬', '판다스', '데이터분석'라는 텍스트가 들어간 데이터를 찾아보자. contains() 메소드를 사용하면 정규표현식을 사용해 원하는 키워드가 들어간 데이터를 찾을 수 있다.

In [69]:
df_python = df[df.text.str.contains(r'.*(파이썬|판다스|데이터분석).*')]
df_python.shape

(435, 17)

In [71]:
df[df.text.str.contains(r'.*(머신러닝|딥러닝).*')].shape

(184, 17)

댓글에 특정 키워드가 포함되어있나 검색해서 있으면 True(1), 없으면 False(0)를 넣은 파생 변수들의 True의 빈도수를 sum() 메소드로 계산한다.

In [75]:
df[search_keyword].sum().sort_values(ascending=False)

파이썬          428
머신러닝         155
딥러닝           73
크롤링           59
데이터분석         36
시각화           30
판다스            6
자연어            4
몽고DB           2
넘파이            0
llm            0
rag            0
langgraph      0
neo4j          0
dtype: int64

In [79]:
text = df.loc[df.데이터분석, 'text']
for t in text:
    print(t)
    print('-' * 100)

웹개발, 데이터분석 하고 싶어서 수업수강 하게 되었어요
관심강의 :  파이썬 입문 수강 중이니까 수강 후에 결정할래용
----------------------------------------------------------------------------------------------------
r 데이터분석의 전문가가 되고싶어용
관심강의 : r로 하는 텍스트마이닝 (top keyword부터 감성분석까지)
----------------------------------------------------------------------------------------------------
퍼포먼스 마케터를 꿈꾸는 학생입니다. 데이터분석 특히 시각화 공부와 더불어서 디지털마케팅전반에 대해 공부하고 싶네요.
관심강의 : 파이썬데이터시각화 분석 실전 프로젝트 , 그로스해킹 - 데이터와 실험을 통해 성장하는 서비스를 만드는 방법
----------------------------------------------------------------------------------------------------
데이터분석가로 변신을 꿈꾸는 직장인입니다. 올해는 r과 파이썬을 마스터하고 싶습니다. 기초 코딩부터 시작해서 머신러닝과 딥러닝까지 도전해보고 싶습니다! 인프런의 강좌들이 많은 도움이 될 것 같습니다! 열공하겠습니다! ^^
관심강의 : r, 파이썬  관련 강의
----------------------------------------------------------------------------------------------------
파이썬 데이터분석 마스터
관심강의:공공데이터로 파이썬 데이터 분석 시작하기
----------------------------------------------------------------------------------------------------
이제 막 군대 전역하는 24살 대학생입니다. 대학 전공은 바이오메디컬이지만 데이터분석과 머신러닝 그리고 앱개발에 관심을 가지고 이제 배움을 시작하려 합니다. 졸업예정자도, 취준생도 아니기 때문에 국비지원 대상자가 아니어서 비싼 학원비가 감당할 수 없던 시점에 인프런이 생각난게 정말 얼마나 다행인지 모릅니다. 풀스택 개발자가 되는 그날까지 함께하겠습니다.
관심강의 "프로그래밍, 데이터 분석을 위한 파이썬 입문", "아이폰 앱 개발(swift4 & ios11) 입문" 입니다.
----------------------------------------------------------------------------------------------------
신입 개발자인데, 현업에서 사용하는 기술의 대부분을 인프런을 통해 배웠습니다.
2020년도 인프런과 함께 하고 싶습니다.
관심강의 : 데이터분석, 텐서플로우, 파이썬 강의
----------------------------------------------------------------------------------------------------
2020년에는 데이터분석 관련한 실력을 쌓고싶습니다!
관심강의 : 파이썬, 판다스, 데이터분석, 머신러닝
----------------------------------------------------------------------------------------------------
머신러닝과 파이썬을 통한 데이터분석 스킬을 기르고 싶어요 !
회사에 있는 많은 데이터를 유의미한 인사이트로 만들어내기 위해 꼭 필요한 스킬 인 것 같아요!

관심강의 : 파이썬 머신러닝 완벽 가이드
----------------------------------------------------------------------------------------------------
데이터분석 2년차가 되는데 작년에 파이썬 강의를 담아놓고 그대로 1년간 방치... 올해는 꼭 완강하고 실습해서 개발자에게 의존하지 않고 혼자 크롤링&분석 해내고 싶어요!
관심강의: 공공데이터로 파이썬 데이터분석 시작하기, database 1&2 - mysql
----------------------------------------------------------------------------------------------------
이직을 위해 개발자 공부를 하려고 합니다~!
관심강의: 파이썬/데이터분석
----------------------------------------------------------------------------------------------------
데이터 분석을 끝내고 싶다.
관심강의: sql/db(mysql) 기본부터 파이썬/데이터분석 활용까지!
----------------------------------------------------------------------------------------------------
데이터분석과 딥러닝 쪽에 관심이 있는데 매번 발만 담궜다 빼는 식으로 봤었는데 2020년 제대로 배워보겠습니다 . 독학으로도 어느정도 수준에 이를 수 있도록 최선을 다하겠습니다.

관심강의 : 파이썬, 딥러닝
----------------------------------------------------------------------------------------------------
데이터분석을 하고 싶은 학생입니다!! 늦었지만 열심히 해서 대학원가고싶어요!!
관심강의: ***의 파이썬 실전  활용
----------------------------------------------------------------------------------------------------
사람들이 무슨 생각을 하는지 알고 싶네요.
관심강의 sql/db(mysql) 기본부터 파이썬/데이터분석 활용까지 입니다.
----------------------------------------------------------------------------------------------------
2020년 데이터분석 전문가가 되기위해 열심히 노력해봅니다!!!!
관심강의 : 모두를 위한 딥러닝
----------------------------------------------------------------------------------------------------
2020년에는 공백기 동안 데이터분석 강의를 들으면서 좀더 전공 능력을 강화시켜 취업에 성공하는 것이 목표입니다.
관심강의: 파이썬 입문 및 웹 크롤링을 활용한 다양한 자동화 어플리케이션 제작하기, 파이썬 크롤링으로 웹 데이터 추출 입문부터 실습까지
----------------------------------------------------------------------------------------------------
그로스해킹에 대한강의를 듣고 싶어요.
마케터로 일하고 있고
고객에게 답이 있다는 그로스 해킹의 기본 개념을 응용해서 좀더 깊이있게 고객정보 분석하고 싶어서 추가적으로 sql이나 파이썬을 배워보고싶습니다.

관심강의
 1. 그로스해킹- 데이터와 실험을 통해 성장하는 서비스를 만드는 방법
2. sql/db(mysql) 기본부터 파이썬/데이터분석 활용까지!
----------------------------------------------------------------------------------------------------
데이터분석가로 취직하기 위해서 sql 시작하고 파이썬 마스터하고 싶습니다!
관심강의: sql/db(mysql) 기본부터 파이썬/데이터분석 활용까지!,
***의 파이썬 실전  활용
----------------------------------------------------------------------------------------------------
sql/db(mysql) 기본부터 파이썬/데이터분석 활용까지!

이 강의 꼭 듣고싶어요!! 서비스기획자인데 mysql을 업무에 실제 어떻게사용할지 고민이거든요!
----------------------------------------------------------------------------------------------------
빅데이터 분석을 공부해서 올해 취직을 목표로 하고있습니다! 첫 사회생활 한다니까 너무 떨려요 후하
열심히 공부해서 취뽀 하고싶어요
관심강의 - sql/db(mysql)기본부터 파이썬/데이터분석 활용까지!
----------------------------------------------------------------------------------------------------
si업체 3년차, 올해는 열심히 준비해서 잠시 잊고 있었던 빅데이터 분야로 이직하고 싶습니다
관심강의_단두장의문서로데이터분석과시각화뽀개기
----------------------------------------------------------------------------------------------------
1학년때 학고.. 제대후 인프런을 통해 학습한 결과 4.0을 맞고 현재 그와 유사한  학점들을 맞으면서  과탑을 유지하는 중입니다. 약 1여년간 안들었는데 다시 초심자의 마음으로 돌아가서 열공모드로 변신하기 위해 신청합니다.
2020년은 인프런을 통해 저를 고급진 사람으로 만들어 주기에 충분합니다.
#adsp는 땄으니깐 데이터분석 전문가인 adp
#cloud가 궁금하다. gcp,aws, naver cloud
----------------------------------------------------------------------------------------------------
인프런으로 파이썬 기초문법부터 입문했어요! 실무 데이터분석에 활용할 수 있는 수준으로 실력을 올리고 싶습니다:)
관심강의: 공공데이터로 파이썬 데이터 분석 시작하기
----------------------------------------------------------------------------------------------------
현재 현업에서 일하고 있습니다.
머신러닝을 마스터하기 위해서 인프런에서 열심히 공부하고 있고 내년도에는 인프런과 함께 성장하는게 제 목표입니다. 인프런에 머신러닝 강의가 잘되어 있어서 항상 만족하며 열공하고 있습니다.
관심강의 : 파이썬 데이터시각화 분석 실전 프로젝트,  파이썬을 활용한 데이터분석과 it보안, [opencv] 파이썬 딥러닝 영상처리 프로젝트 - ***을 찾아라!
----------------------------------------------------------------------------------------------------
2020년에는 그로스해커로 거듭나서 우리회사 서비스도 발전시키고, 열매를 맺히게하자앗-!??

그로스해킹-데이터분석과 실험으로 성장시키기 강의 관심있어용?????♀?
----------------------------------------------------------------------------------------------------
올해로 지천명 혹은 반백의 나이...하지만 지난 2,3년은 나의 의지와 관심만 있다면 무엇이든 새로 배움에 있어 포지션과 나이는 중요치 않다는 걸 확신한 시기였습니다. 나의 직업은 개발자가 아니지만 새로운 비즈니스를 구상하며 웹 개발, 데이터분석 등 하나하나 교양과목 듣듯 배워나겠습니다. 모두 화이팅!!
관심강의: 실습 ui 개발로 배워보는 순수 자바스크립트 와 vuejs 개발, 파이썬입문과 크롤링기초 부트캠프 등
----------------------------------------------------------------------------------------------------
저는 정보보안학과 학생이에요! 이제 2학년으로 올라가게되는데 실무를 위해서 많은 공부와 경험을 하고싶습니다!!
#취미로해킹#1-#5 ,화이트해커가 되기위한 모의해킹 완전정복 , 리버싱 이정도는 알아야지 ,파이썬을 활용한 데이터분석과 it보안,it 취업을 위한 알고르즘 입문(wit c++)창의적 문제해결
----------------------------------------------------------------------------------------------------
파이썬관련하여 공부를 더 열심히 하고 싶어요!
관심 강의 : sql/db(mysql) 기본부터 파이썬/데이터분석 활용까지!
----------------------------------------------------------------------------------------------------
파이썬을 이용한 데이터분석에 관심이 생겨서 공부하려고 합니다. 목표를 꼭 달성했으면 좋겠어요!
2020년 목표 : sql문법과 파이썬에 익숙해지기
관심 강의 : sql/db(mysql) 기본부터 파이썬/데이터분석 활용까지!
----------------------------------------------------------------------------------------------------
올해는 파이썬으로 꼭 데이터분석을 하고 싶습니다.
41살에 시작한 늦은 나이에 시작한 코딩 공부 이지만, 올해는 꼭 제 몸값을 올릴 수 있는 공부를 하고 싶네요^^
플랫폼 기획자로 15년 넘도록 근무했지만, 파이썬으로 데이터 분석도 할 수 있는 개발자의 능력도 갖춘 그런 제가 되었으면 좋겠습니다.

관심강의 : 파이썬, 자바, 스프링부트, 알고리즘
----------------------------------------------------------------------------------------------------
인프런은 학교수업으로 부족한 저의 코딩 실력을 매꾸어 주는곳 입니다.
항상 복습할 강의가 있으면 인프런으로 수강할 과목을 수강하고
매번 새로운 강의가 올라오니 듣고싶은것알 다양하게 수강할 수 있어서 좋은것 같습니다.
올해 강의를 더 많이 수강해서 달라지는 저의 모습을 보고 싶습니다.
관심강의 : 스프링 데이터 jpa, 파이썬 데이터분석
----------------------------------------------------------------------------------------------------
저의 커리어를 더 심도있게 공부하고 싶은 2020년입니다! 데이타분석과 그로스해킹쪽을 더 공부하고 싶네요. 좋은 기회를 주셔서 감사합니다.

관심강의 : 데이터분석 , 그로스해킹, 디지털마케팅
----------------------------------------------------------------------------------------------------
저는 백세시대에 조금 더 오랫동안 it일을 하기위해서 it전략기획에서 데이터분석가로 커리어 전환을 준비하고 있습니다. 인프런의 수많은 좋은 강의중 파이썬 기반의 데이터분석을 공부하기 위하여 인프런을 활용하고 있습니다. 대한민국 최고의 데이터분석가 되는 그날까지 인프런과 함께 하겟습니다.
관심강의 : 파이썬 판다스 데이터 분석과 시각화 뽀개기등 데이터분석 관련 강의
----------------------------------------------------------------------------------------------------
올해는 데이터 분석과 머신러닝쪽을 마스터하고 싶어요

#파이썬,데이터분석, 빅데이터분석
----------------------------------------------------------------------------------------------------
저번에 인프런에서 페이스북 마케팅 강의를 듣고 많은 도움을 받았습니다. 마케팅 업무를 하다보니, 데이터분석에 관심을 갖게 되어 올해는 꼭 프로그래밍을 이용한 데이터분석을 인프런에서 공부하고 시도해보고 싶습니다.
관심강의 : 파이썬 입문 및 웹 크롤링을 활용한 다양한 자동화 어플리케이션 제작하기
----------------------------------------------------------------------------------------------------

In [80]:
text = df.loc[df.판다스, 'text']
for t in text:
    print(t)
    print('-' * 100)

2020년에는 데이터분석 관련한 실력을 쌓고싶습니다!
관심강의 : 파이썬, 판다스, 데이터분석, 머신러닝
----------------------------------------------------------------------------------------------------
취미로 안드로이드 개발하는 사람입니다. 자바로 작성하다 보니, kotlin이 안드로이드 기반언어로 바뀌어서 새로 배워보려고 합니다.
관심강의 : kotlin, 판다스, 파이썬, c언어
----------------------------------------------------------------------------------------------------
판다스 라입러리에 관심이 많아서 배워보려 합니다 관심강의 : *** 판다스
----------------------------------------------------------------------------------------------------
2020년!! 올 해는 빅데이터 분석 전문가 되기!!
관심강의 : 파이썬, 판다스
----------------------------------------------------------------------------------------------------
2020년 목표  파이썬 을  활용해  데이터 분석 작업을 진행하고 싶습니다.  관심강의:파이썬 판다스 관련 강좌 입니다
----------------------------------------------------------------------------------------------------
저는 백세시대에 조금 더 오랫동안 it일을 하기위해서 it전략기획에서 데이터분석가로 커리어 전환을 준비하고 있습니다. 인프런의 수많은 좋은 강의중 파이썬 기반의 데이터분석을 공부하기 위하여 인프런을 활용하고 있습니다. 대한민국 최고의 데이터분석가 되는 그날까지 인프런과 함께 하겟습니다.
관심강의 : 파이썬 판다스 데이터 분석과 시각화 뽀개기등 데이터분석 관련 강의
----------------------------------------------------------------------------------------------------

# 벡터화 하기