In [1]:
import warnings
warnings.filterwarnings(action='ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
gapminder_df = pd.read_csv('./data/gapminder.tsv', sep='\t')
gapminder_df.head(3)

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710

그룹화

groupby() 메소드를 사용해서 특정 열을 기준으로 데이터를 그룹화할 수 있다.

In [3]:
# lifeExp_by_year = gapminder_df.groupby('year')['lifeExp'].mean()
lifeExp_by_year = gapminder_df.groupby('year').lifeExp.mean()
lifeExp_by_year

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [4]:
lifeExp_by_year = gapminder_df.groupby(['continent', 'year'])[['lifeExp', 'pop']].mean()
lifeExp_by_year

                  lifeExp           pop
continent year
Africa    1952  39.135500  4.570010e+06
          1957  41.266346  5.093033e+06
          1962  43.319442  5.702247e+06
          1967  45.334538  6.447875e+06
          1972  47.450942  7.305376e+06
          1977  49.580423  8.328097e+06
          1982  51.592865  9.602857e+06
          1987  53.344788  1.105450e+07
          1992  53.629577  1.267464e+07
          1997  53.598269  1.430448e+07
          2002  53.325231  1.603315e+07
          2007  54.806038  1.787576e+07
Americas  1952  53.279840  1.380610e+07
          1957  55.960280  1.547816e+07
          1962  58.398760  1.733081e+07
          1967  60.410920  1.922986e+07
          1972  62.394920  2.117537e+07
          1977  64.391560  2.312271e+07
          1982  66.228840  2.521164e+07
          1987  68.090720  2.731016e+07
          1992  69.568360  2.957096e+07
          1997  71.150480  3.187602e+07
          2002  72.422040  3.399091e+07
          2007  73.608120  3.595485e+07
Asia      1952  46.314394  4.228356e+07
          1957  49.318544  4.735699e+07
          1962  51.563223  5.140476e+07
          1967  54.663640  5.774736e+07
          1972  57.319269  6.518098e+07
          1977  59.610556  7.225799e+07
          1982  62.617939  7.909502e+07
          1987  64.851182  8.700669e+07
          1992  66.537212  9.494825e+07
          1997  68.020515  1.025238e+08
          2002  69.233879  1.091455e+08
          2007  70.728485  1.155138e+08
Europe    1952  64.408500  1.393736e+07
          1957  66.703067  1.459635e+07
          1962  68.539233  1.534517e+07
          1967  69.737600  1.603930e+07
          1972  70.775033  1.668784e+07
          1977  71.937767  1.723882e+07
          1982  72.806400  1.770890e+07
          1987  73.642167  1.810314e+07
          1992  74.440100  1.860476e+07
          1997  75.505167  1.896480e+07
          2002  76.700600  1.927413e+07
          2007  77.648600  1.953662e+07
Oceania   1952  69.255000  5.343003e+06
          1957  70.295000  5.970988e+06
          1962  71.085000  6.641759e+06
          1967  71.310000  7.300207e+06
          1972  71.910000  8.053050e+06
          1977  72.855000  8.619500e+06
          1982  74.290000  9.197425e+06
          1987  75.320000  9.787208e+06
          1992  76.945000  1.045983e+07
          1997  78.190000  1.112072e+07
          2002  79.740000  1.172741e+07
          2007  80.719500  1.227497e+07

groupby() 메소드와 같이 사용하는 그룹 함수

count(): 누락값을 제외한 그룹별 데이터의 개수  
size(): 누락값을 포함한 그룹별 데이터의 개수  
sum(): 누락값을 제외한 그룹별 데이터의 합계  
mean(): 누락값을 제외한 그룹별 데이터의 평균  
max(): 누락값을 제외한 그룹별 데이터의 최대값  
min(): 누락값을 제외한 그룹별 데이터의 최소값  
var(): 누락값을 제외한 그룹별 데이터의 분산  
std(): 누락값을 제외한 그룹별 데이터의 표준편차  
quantile(q=0.25): 누락값을 제외한 그룹별 데이터의 1사분위수  
quantile(q=0.5): 누락값을 제외한 그룹별 데이터의 2사분위수, 중위수  
quantile(q=0.75): 누락값을 제외한 그룹별 데이터의 3사분위수  
describe(): 누락값을 제외한 그룹별 데이터의 개수, 평균, 표준편차, 최소값, 1사분위수, 2사분위수, 3사분위수, 최대값  
sem(): 누락값을 제외한 그룹별 데이터의 평균의 표준편차  
first(): 그룹별 데이터의 첫 번째 데이터  
last(): 그룹별 데이터의 마지막 데이터  
nth(): 그룹별 데이터의 n번째 데이터

groupby() 메소드와 같이 사용되는 그룹 함수들은 groupby() 메소드 뒤에 '.'을 찍고 실행하면 되지만 사용자 정의 함수 groupby() 메소드 뒤에 '.'을 찍어서 바로 실행할 수 없고 agg() 메소드를 사용해서 일괄 적용시켜야 한다.

In [5]:
# 숫자 데이터가 저장된 리스트를 인수로 넘겨받아 평균을 계산해서 리턴하는 함수
def my_mean(values):
    n = len(values)
    total = 0
    for value in values:
        total += value
    return total / n

In [6]:
print(my_mean([1, 2, 3, 4, 5]))

3.0

In [7]:
# 사용자 정의 함수를 groupby()가 제공하는 집계 함수처럼 사용하려하면 계산 데이터가 전달되지 않아서 에러가 발생된다.
# gapminder_df.groupby('year').lifeExp.my_mean() # 에러

# 사용자 정의 함수를 groupby() 메소드에서 사용하려면 agg() 메소드의 인수로 함수 이름만 넘겨주면 된다. 함수 이름 뒤에 ()를 입력하면 안된다.
# agg() 메소드는 agg() 메소드를 실행하는 그룹의 데이터가 자동으로 agg() 메소드의 인수로 지정한 사용자 정의 함수의 인수로 전달한다.
gapminder_df.groupby('year').lifeExp.agg(my_mean)

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [8]:
# year 별로 계산된 그룹 평균과 전체 평균의 편차를 계산해서 리턴하는 함수
def my_mean_diff(values, global_mean):
    n = len(values)
    total = 0
    for value in values:
        total += value
    mean = total / n # 그룹의 평균
    return mean - global_mean

In [9]:
global_mean = gapminder_df.lifeExp.mean()
print(global_mean)

59.474439366197174

In [10]:
# agg() 메소드가 사용자 정의 함수의 첫 번째 인수로 그룹 데이터를 전달하고 두 번째 인수는 agg() 메소드의 인수로 지정해서 넘긴다.
gapminder_df.groupby('year').lifeExp.agg(my_mean_diff, global_mean)

year
1952   -10.416820
1957    -7.967038
1962    -5.865190
1967    -3.796150
1972    -1.827053
1977     0.095718
1982     2.058758
1987     3.738173
1992     4.685899
1997     5.540237
2002     6.220483
2007     7.532983
Name: lifeExp, dtype: float64

그룹화한 결과에 numpy 집계 메소드 실행하기

numpy 집계 메소드를 실행하려면 딕셔너리에 계산에 사용할 열 이름을 key로 지정하고 실행할 numpy 메소드 이름을 value로 지정해서 전달한다.

In [11]:
numpy_group = gapminder_df.groupby('year').agg({'lifeExp': 'sum', 'pop': 'mean', 'gdpPercap': 'median'})
numpy_group

         lifeExp           pop    gdpPercap
year
1952  6966.18200  1.695040e+07  1968.528344
1957  7314.05096  1.876341e+07  2173.220291
1962  7612.51336  2.042101e+07  2335.439533
1967  7906.31712  2.265830e+07  2678.334740
1972  8185.92888  2.518998e+07  3339.129407
1977  8458.96236  2.767638e+07  3798.609244
1982  8737.71400  3.020730e+07  4216.228428
1987  8976.19100  3.303857e+07  4280.300366
1992  9110.76800  3.599092e+07  4386.085502
1997  9232.08400  3.883947e+07  4781.825478
2002  9328.67900  4.145759e+07  5319.804524
2007  9515.05400  4.402122e+07  6124.371108

표준 점수 계산하기

데이터의 평균과 표준편차의 차이를 표준 점수라 부른다.  
표준 점수의 표준편차를 계산하면 변환된 데이터에 평균이 0이 표준편차가 1이된다. 그러면 데이터가 표준화되서 서로 다른 데이터를 쉽게 비교할 수 있다.

agg() 메소드는 그룹화된 데이터를 사용자 정의 함수에 전달해서 그룹별 대표값 1개를 만들지만 transform() 메소드는 그룹화된 데이터를 사용자 함수에 전달해서 그룹별 데이터 각각에 대한 결과를 만든다.

In [12]:
def my_zscore(x):
    return (x - x.mean()) / x.std()

In [13]:
gapminder_df['agg_mean'] = gapminder_df.groupby('year').lifeExp.agg(my_mean)
gapminder_df['transform_zscore'] = gapminder_df.groupby('year').lifeExp.transform(my_zscore)
gapminder_df.head(3)

,country,continent,year,lifeExp,pop,gdpPercap,agg_mean,transform_zscore
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,NaN,-1.656854
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,NaN,-1.731249
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,NaN,-1.786543

누락값을 평균값으로 처리하기

seaborn 라이브러리의 tips 데이터셋에서 무작위로 10개의 행 데이터를 가져온 다음 total_bill 열의 값 4개를 임의로 선택해서 누락값으로 바꾼다.
매번 실행할 때 마다 같은 배열의 데이터를 추출하기 위해 seed() 메소드로 난수를 고정한다.

In [14]:
np.random.seed(6)
# sample() 메소드는 인수로 지정한 개수만큼 전체 데이터에서 데이터를 랜덤하게 추출한다.
tips_df = sns.load_dataset('tips').sample(10)
tips_df

     total_bill   tip     sex smoker   day    time  size
164       17.51  3.00  Female    Yes   Sun  Dinner     2
166       20.76  2.24    Male     No   Sun  Dinner     2
19        20.65  3.35    Male     No   Sat  Dinner     3
223       15.98  3.00  Female     No   Fri   Lunch     3
17        16.29  3.71    Male     No   Sun  Dinner     3
238       35.83  4.67  Female     No   Sat  Dinner     3
118       12.43  1.80  Female     No  Thur   Lunch     2
87        18.28  4.00    Male     No  Thur   Lunch     2
13        18.43  3.00    Male     No   Sun  Dinner     4
196       10.34  2.00    Male    Yes  Thur   Lunch     2

x = np.arange(10)  
print(x) # [0 1 2 3 4 5 6 7 8 9]이 출력된다. => 원본  
print(np.random.permutation(x)) # 섞인 결과가 출력된다.  
print(x) # [0 1 2 3 4 5 6 7 8 9]이 출력된다. => permutation() 메소드는 원본을 변형시키지 않는다. 섞은 결과를 리턴한다.  
print(np.random.shuffle(x)) # None이 출력된다.  
print(x) # shuffle() 메소드에 의해서 섞인 결과가 출력된다. => shuffle() 메소드는 원본을 변형시킨다. 리턴값이 없다.

In [15]:
tips_df.loc[np.random.permutation(tips_df.index)[:4], 'total_bill'] = np.nan
tips_df

     total_bill   tip     sex smoker   day    time  size
164         NaN  3.00  Female    Yes   Sun  Dinner     2
166         NaN  2.24    Male     No   Sun  Dinner     2
19        20.65  3.35    Male     No   Sat  Dinner     3
223       15.98  3.00  Female     No   Fri   Lunch     3
17        16.29  3.71    Male     No   Sun  Dinner     3
238       35.83  4.67  Female     No   Sat  Dinner     3
118         NaN  1.80  Female     No  Thur   Lunch     2
87          NaN  4.00    Male     No  Thur   Lunch     2
13        18.43  3.00    Male     No   Sun  Dinner     4
196       10.34  2.00    Male    Yes  Thur   Lunch     2

In [16]:
# total_bill 열의 누락값을 total_bill 열 전체의 평균으로 채우기
tips_df.total_bill.fillna(tips_df.total_bill.mean())

164    19.586667
166    19.586667
19     20.650000
223    15.980000
17     16.290000
238    35.830000
118    19.586667
87     19.586667
13     18.430000
196    10.340000
Name: total_bill, dtype: float64

In [17]:
# tips_df의 데이터에는 여성보다 남성이 더 많기 때문에 여성과 남성을 구분해서 total_bill 열의 평균을 계산하지 않으면 여성 데이터가 남성 데이터의 영향(간섭)을
# 받아서 여성 데이터가 회손될 수 있다.
count_sex = tips_df.groupby('sex').count()
count_sex

        total_bill  tip  smoker  day  time  size
sex
Male             4    6       6    6     6     6
Female           2    4       4    4     4     4

In [18]:
print('total_bill 전체 평균: {}'.format(tips_df.total_bill.mean()))
print(tips_df.groupby('sex').total_bill.mean())

total_bill 전체 평균: 19.58666666666667
sex
Male      16.4275
Female    25.9050
Name: total_bill, dtype: float64

In [19]:
# 성별별로 그룹화해서 total_bill 열의 데이터를 받아 평균을 계산해서 성별별 평균을 누락값으로 수정하는 함수
def fillna_mean(values):
    avg = values.mean() # 성별별 평균을 계산한다.
    return values.fillna(avg)

In [20]:
tips_df.groupby('sex').total_bill.transform(fillna_mean)

164    25.9050
166    16.4275
19     20.6500
223    15.9800
17     16.2900
238    35.8300
118    25.9050
87     16.4275
13     18.4300
196    10.3400
Name: total_bill, dtype: float64